### ISSUE TITLE
how to use git-bash as default shell on windows

### ISSUE THREAD

**Issue by inksnw** [randy3k/Terminus#10]
i try to modify Terminus.sublime-settings like this but it open a new window for git-bash,can git-bash work on windows? thank you
git-bash: https://git-scm.com/downloads
{
            "name": "git-bash",
            "cmd": "git-bash.exe",
            "env": {},
            "enable": true,
            "default": true,
            "platforms": ["windows"]
        },

**Comment by randy3k** [comment]
AFAIK, git-bash.exe is a GUI program . You should open the bash.exe which comes with it.

**Comment by inksnw** [comment]
it works thank you, really cool

**Comment by rivetweb** [comment]
can you provide example for Windows ?

**Comment by randy3k** [comment]
It really depends on your setup. Please provide some information about your installation of bash.

**Comment by rivetweb** [comment]
> It really depends on your setup. Please provide some information about your installation of bash.

i install this git bash https://gitforwindows.org

**Comment by esyede** [comment]
This is my (working) config for git bash, I don't know if it's the correct way or not but it works for me:

```json
{
    "default_config": {
        "linux": null,
        "osx": null,
        "windows": "git-bash", // must be identical with the shell config name
    },
    "shell_configs": [
        {
            "name": "git-bash", // i mean, this one
            "cmd": ["D:/Laragon/bin/git/bin/bash.exe"], // you need to adjust this too
            "env": {},
            "enable": true,
            "default": true,
            "platforms": ["windows"],
        }
    ],
    "theme": "darkside",
}
```



<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/19880d54-f3a3-474d-af05-1bff8263b5f0" />
