### ISSUE TITLE
Args for terminus when using in build system?

### ISSUE THREAD

**Issue by YuriGor** [randy3k/Terminus#100]
Hi, thank you for the plugin!
I'd like terminus to mimic default build systems behavior, so it will not open new tab,
but do the horizontal split.
Here is my latest attempt to do this in my "test" build system:

```json
{
  "cmd": [
    "/home/gor/.nvm/versions/node/v11.9.0/bin/npm",
    "run-script",
    "test",
    "$file"
  ],
  "working_dir": "$folder",
  "target": "terminus_open",
  "auto_close": false,
  "args": {
    "config_name": "Default",
    "post_window_hooks": [
      [
        "carry_file_to_pane",
        {
          "direction": "down"
        }
      ]
    ]
  }
}
```
As expected, "args" field is not accepted by build system, so how to deal with it?

**Comment by YuriGor** [comment]
It works without nesting terminus options into "args"
```json
{
  "cmd": [
    "/home/gor/.nvm/versions/node/v11.9.0/bin/npm",
    "run-script",
    "test",
    "$file"
  ],
  "working_dir": "$folder",
  "target": "terminus_open",
  "auto_close": false,
  "config_name": "Default",
  "post_window_hooks": [
    [
      "carry_file_to_pane",
      {
        "direction": "down"
      }
    ]
  ]
}
```

**Comment by hwonsok** [comment]
I have the same problem right now and am not able to find a solution to this.
A new Terminus tab is open every time I build a system.

Has anyone been able to find a workaround?
