### ISSUE TITLE
Powerline Fonts

### ISSUE THREAD

**Issue by wishinghand** [randy3k/Terminus#102]
I'm using Zsh with the Agnoster theme that includes Powerline fonts. When I open a new Terminus view, whether in a tab or the console, some of the icons don't render properly. I searched the README and didn't find any mention of enabling these. I think it may be something to do with the `cmd` argument. Has anyone been able to figure this out?

<img width="597" alt="image" src="https://user-images.githubusercontent.com/4001750/55528153-becd2a80-5650-11e9-8221-9d3a385ad134.png">

**Comment by randy3k** [comment]
You will need to change the font of sublime text, or change the font of Terminus views in Terminus settings.

**Comment by wishinghand** [comment]
Ah, silly me. I don't know why I didn't think of that.

**Comment by identifysun** [comment]
This question already solves in the new version. Please add following config in Terminus settings.

```
    "view_settings": {
        // these are extra view settings which are passed to the terminus_view,
        // you could change settings like "font_face", "font_size" and paddings.
        "font_face": "Menlo for Powerline"
    }
```

**Comment by tianshaohan** [comment]
I have try, but it noting
![image](https://user-images.githubusercontent.com/58108746/175887902-a725ea4a-bdaa-42c5-be1e-81829fbe40de.png)

**Comment by minlmao** [comment]
> I install this font
> 
> https://github.com/romkatv/dotfiles-public/blob/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf
> 
> And change to
> 
> `"view_settings":{ "font_face": "MesloLGS NF", "font_size": 12 },`
> 
> ```
> Then it is working now
> ```

I think Terminus doesn't support font ligatures.
