### ISSUE TITLE
Unknown option '-l'

### ISSUE THREAD

**Issue by DeeeeLAN** [randy3k/Terminus#106]
The default shell in my environment is tcsh. I haven't configured terminus at all, just installed it then attempted to launch the default shell. It appears to be using tcsh, but fails with the following output:

```
Unknown option: `-l'
Usage: tcsh [ -bcdefilmnqstvVxX ] [ argument ... ].

process is terminated with return code 1.
```

Any ideas?

**Comment by DeeeeLAN** [comment]
I added tcsh as a shell option where I was able to customize the flags. the man page for tcsh specifies:

```
-i  The shell is interactive and prompts for its top-level input, even if it appears to not be a terminal.  Shells are interactive without this option if their inputs and outputs are terminals.
-l  The shell is a login shell.  Applicable only if -l is the only flag specified.
```

I am not sure which flag is preferred in this case, but I am going to go with -l for now.

**Comment by randy3k** [comment]
Oh it seems that tcsh does not support the `-l` flag. Currently we open the default shell with a `-l` flag.
As a workaround for now, you will need to define a default shell via the Terminus Preferences.

I will push a fix for this issue once I have time.

**Comment by DeeeeLAN** [comment]
It supports `-l`, but only by itself. So you would need to drop the `-i` flag when launching tcsh.
