### ISSUE TITLE
Open file for editing from terminus

### ISSUE THREAD

**Issue by DeeeeLAN** [randy3k/Terminus#107]
Is there a way to open a file for editing in ST from terminus? I would love to navigate directories, then be able to pull either run a command or otherwise select the file in a directory for editing within my current ST window.

**Comment by randy3k** [comment]
Won't you could use `subl <the file>`?

**Comment by DeeeeLAN** [comment]
Yes, I was able to get that to work. My environment was screwed up, so you helped me fix it, thanks.
