### ISSUE TITLE
Memory issue clarification

### ISSUE THREAD

**Issue by Svish** [randy3k/Terminus#111]
> It is because Sublime Text keeps an infinite undo stack.

Is this the case for both the panel and the view? Or just the view? And does Terminus clear memory itself when closing the terminal? For example when running `exit` in a Terminus panel, which closes the panel?

**Comment by randy3k** [comment]
It applies to both panel and regular view. Yes, the memory will be clear when the terminal is closed.

This memory issue only arises after a terminal is opened after a very long period of time or when there are a lot of printings in a terminal. It usually won't be noticeable with regular uses.

**Comment by Svish** [comment]
Right, makes sense! Thanks for quick reply. 🙂

Maybe add a notice to the readme about memory being cleared when closed? Or perhaps that the memory issue is for long running terminals, or something. Because, yeah, I got the impression that memory was never cleared, and only way was to use the reset thing. 🤔
