### ISSUE TITLE
Terminus steals focus and close then reopen views with `pscid` running in them 

### ISSUE THREAD

**Issue by kl0tl** [randy3k/Terminus#112]
There’s something weird happening with [`pscid`](https://github.com/kRITZCREEK/pscid) running in a Terminus view and split panes layout since `v0.2.29`:

+ If the setting `origami_auto_close_empty_panes` is `true`:
  * If Terminus is the only view in the pane, Origami closes it when `pscid` is launched.
    - If moved back to another pane (and still the only view in it), the Terminus view is moved to the pane of the current view _and_ it’s original pane steals focus on save.
  * Otherwise if there’s another view in the pane it looks like the view is cleared, then rerendered and the it’s tab is moved last (like if it was closed then reopened).
    - The Terminus view then steals focus from the current view on save.
+ Setting `origami_auto_close_empty_panes` to `false` doesn’t change much, except Origami doesn’t close the pane when Terminus is the only view in it and `pscid` is launched.

It worked like a charm in `v0.2.28`.

**Comment by randy3k** [comment]
Tried restarting sublime?

**Comment by kl0tl** [comment]
Yes I did, but it doesn’t change anything.

**Comment by randy3k** [comment]
Actually, the bug was caused by a commit which handles the `reset` command. The same bug could be also reproduced by the `reset` command.

**Comment by randy3k** [comment]
v0.2.31 should fix it.
