### ISSUE TITLE
/bin/bash npm: command not found

### ISSUE THREAD

**Issue by alexbet** [randy3k/Terminus#117]
Hi, 

I am using nvm to control the Node version. This was working up until now. Sometimes I had to reconfirmthe Node version by "nvm use --lts" in order for it to work in Terminus, but it was working. All of a sudden, it doesn't work and I am getting this error:

> /bin/bash: npm: command not found
> process is terminated with return code 127.

Here is my config:

{
  "cmd":
  [
    "bash", "-c", "npm run serve"
  ],
  "name": "NPM Serve",
  "target": "terminus_open",
  "working_dir": "$folder/build",
  "auto_close": false
},

Just FYI, if I do this in iTerm, it works fine, so I am not sure why it is not working in Terminus. 

Any help is appreciated. 
Thanks!

**Comment by alexbet** [comment]
BTW, if I open a new Terminus bash window and type "npm run serve" it works fine.

**Comment by randy3k** [comment]
You might need a login flag.

```
"bash", "-l", "-c", "npm run serve"
```

**Comment by alexbet** [comment]
@randy3k , that worked! Thanks!
