### ISSUE TITLE
Caret color cannot be changed...

### ISSUE THREAD

**Issue by JW9506** [randy3k/Terminus#118]
![Kapture 2019-05-12 at 0 31 18](https://user-images.githubusercontent.com/34848995/57577813-7b36bf00-744d-11e9-902a-fe89fe637355.gif)

I made the caret wider by modifying commands.py and then the above was my attempt to change the caret color... Not sure if I am doing the right thing but all I wanted to achieve is to make the character underneath the caret to show a distinguishable color(like pure black). I am currently using the Darkside color scheme. Added a couple of settings in the Darkside.json file but I cannot see the effect!
Thanks Randy~

**Comment by randy3k** [comment]
First, you should not modify the json file directly. Use the settings in Terminus settings for customizing the theme. Second, if you edited a json file, you will need to select the Dark theme again or rebuild the theme file to see the changes in it.

**Comment by randy3k** [comment]
Oh, I see that you added several view settings too, for example the block caret....you should again add them via the Terminus Preference.

**Comment by randy3k** [comment]
Lastly, IIRC, there are no settings for changing the foreground of the caret. https://www.sublimetext.com/docs/3/color_schemes.html

**Comment by JW9506** [comment]
Can you show me steps to properly edit a json file (say darkside theme json file), let's say I want to add a `caret` and `block_caret` properties under darkside theme? Also... I don't understand what you mean by rebuilding a theme file.... How do you do it?

**Comment by JW9506** [comment]
I used `grep -R caret .` to locate all the caret settings... I straight up editing the source rather than editing the preference inside sublime...

**Comment by JW9506** [comment]
I guess my goal is to 'invert'(like black->white, white->black) the color of whichever character is under the caret at the moment.

**Comment by randy3k** [comment]
>Can you show me steps to properly edit a json file (say darkside theme json file), let's say I want to add a `caret` and `block_caret` properties under darkside theme? Also... I don't understand what you mean by rebuilding a theme file.... How do you do it?

@JW9506 there is a command to select theme in the command platelets.

**Comment by randy3k** [comment]
>I used `grep -R caret .` to locate all the caret settings... I straight up editing the source rather than editing the preference inside sublime...

@JW9506 you are likely to lose the changes if you modify the source directly and when package control upgrades a new version of Terminus

**Comment by randy3k** [comment]
>I guess my goal is to 'invert'(like black->white, white->black) the color of whichever character is under the caret at the moment.

@JW9506 I don’t think it is possible with the current implementation of Sublime Text.

**Comment by JW9506** [comment]
Eh okay~
