### ISSUE TITLE
[Question] Font size in panel

### ISSUE THREAD

**Issue by duranivan** [randy3k/Terminus#121]
Hi and thanks for a great addition to sublime.

I was wondering if it is possible to change the font size of the terminus panel. At the moment is quite small so I would like to increase its font size.

I'm using the DA UI theme but couldn't find in the settings how to control the panel font size.

Thanks in advance!

**Comment by randy3k** [comment]
You could specify the font size in `view_settings`.
```
    "view_settings": {
        "font_size": 10
    }
```

**Comment by duranivan** [comment]
Thanks, it works like a charm!
