### ISSUE TITLE
TrailingSpaces being applied to Terminus

### ISSUE THREAD

**Issue by heitorsilva** [randy3k/Terminus#122]
Hey guys!

I'm using Terminus on Sublime 3207, and I noticed that the [Trailing Spaces](https://github.com/SublimeText/TrailingSpaces) plugin is being applied to the terminal Output. The spaces are being highlighted with my rules...

![Screenshot 2019-05-20 at 15 56 03](https://user-images.githubusercontent.com/878699/58026929-e2bcd080-7b17-11e9-982d-4d97f15b509d.png)

Is there a way to turn that off only for the terminal?

**Comment by rchl** [comment]
This should be fixed in latest version of TrailingSpaces.

**Comment by randy3k** [comment]
Thanks @rchl
