### ISSUE TITLE
Theme not being applied properly

### ISSUE THREAD

**Issue by duranivan** [randy3k/Terminus#124]
If I use the Sublime Monokai Pro theme for some reason the Terminus themes are not applied properly. In the screen shot I am using Ocean Next for terminus and  Monokai Pro for Sublime:

![Screen Shot 2019-05-25 at 2 48 34 PM](https://user-images.githubusercontent.com/20104703/58367766-36eef880-7efc-11e9-9139-a4013a524718.png)

As you can see, only some parts with text have glimpses of the Terminus Ocean Next theme. I have only seen this behavior with the Sublime Monokai Pro theme (regardless of the Terminus theme). With other Sublime themes it works just fine, e.g. Adaptive, DA UI, etc.

Any ideas why this can be happening and how to solve it?

Thanks in advance!

**Comment by randy3k** [comment]
It is a known bug of sublime rendering system. To be more specific, your theme have defined a custom panel background color. You could fix it by changing the background of the panel to the background of a regular view. But it involves some work of your theme file.

**Comment by duranivan** [comment]
Alright, thanks. It's not that of a big issue so I won't mess up with the theme.
