### ISSUE TITLE
[Feature] Toggle View

### ISSUE THREAD

**Issue by idr4n** [randy3k/Terminus#125]
Hi,

I know i can toggle the panel with `alt+'` and also to maximize to view from panel as well as minimize.

Is there a way to toggle the terminus shell when opened in view mode? I am using the suggested origami setup to open in view mode:

```
  {
    "keys": ["ctrl+alt+t"],
    "command": "terminus_open",
    "args": {
      "post_window_hooks": [
        ["carry_file_to_pane", {"direction": "down"}]
      ]
    }
  },
```

It would be great if i can toggle the view opened with the origami command.

**Comment by randy3k** [comment]
Do you mean switching the focus to the terminal view?

**Comment by duranivan** [comment]
I mean something like what `alt+'` does for the panel but for the view. I don't know if it makes sense?

**Comment by randy3k** [comment]
Well, a regular view doesn’t toggle.
