### ISSUE TITLE
The last update generated this bug

### ISSUE THREAD

**Issue by jmdev33376** [randy3k/Terminus#14]
Hi, 
the last update generated this bug on ST build 3176.

![screen shot 2018-07-03 at 01 40 17](https://user-images.githubusercontent.com/39066958/42192850-5bafd486-7e63-11e8-824a-e81a2de8ee8e.png)

When we try to remove your package, the result is this:

![screen shot 2018-07-03 at 01 53 47](https://user-images.githubusercontent.com/39066958/42192987-0e538fba-7e64-11e8-839e-36d00bf15dca.png)

Without Terminus, everything works fine:

![screen shot 2018-07-03 at 01 55 54](https://user-images.githubusercontent.com/39066958/42193031-419b74b4-7e64-11e8-99df-ebbe9d5ae7d7.png)

**Comment by randy3k** [comment]
Oh. Thanks for the report.

**Comment by randy3k** [comment]
It is fixed in v0.1.4.
