### ISSUE TITLE
try to enter and exit ide by double clicking keyboard accelerators.

### ISSUE THREAD

**Issue by inksnw** [randy3k/Terminus#15]
```py
class enteride(sublime_plugin.WindowCommand):
    # enter python
    def run(self, ide):
        global already_in_ide

        if not already_in_ide:
            self.window.run_command("toggle_terminus_panel")

            self.window.run_command("terminus_send_string",
                                    {"string": "{}\n".format(ide),
                                     "tag": None}
                                    )
            already_in_ide = True
        else:
            if ide == "python":
                exit_cmd = "exit();"
            elif ide == "node":
                exit_cmd = "process.exit();"
            self.window.run_command(
                "terminus_send_string",
                {
                    "string": "{}\nclear\n".format(exit_cmd),
                    "tag": None        # or the tag which is passed to "terminus_open"
                }
            )
            already_in_ide = False`
```

try to use new api  Terminus Command Palette in v0.1.4 to enter and exit ide by double clicking shortcuts ,but in my bash.exe  everytime it open a new tab,and i can't use toggle_terminus_panel it  to open it,so i make my own python script like this,but i still has many bugs like already_in_ide not ensure and exit command not same in many ides like node,python....sorry for my english

**Comment by inksnw** [comment]
try to format code

**Comment by randy3k** [comment]
I am not sure what you want to achieve, specifically, what do you mean when you say "double clicking shortcuts"?

**Comment by inksnw** [comment]
sorry,i mean that
1. one tap enter ide and tap again exit it
2. open it in toggle_terminus_panel
3. not mayng tabs ,just one

**Comment by randy3k** [comment]
So, you want to open python or node in the panel and exit the program when the panel hides.

1. do you want the same panel for both programs?
2. how do you want it to be triggered? via a keybind or via the command palette?

**Comment by inksnw** [comment]
1. may have a config for use same panel or not?
2. prefer keybind

**Comment by randy3k** [comment]
I have just push v0.1.5

It has some utilities to make things a bit eaiser

```
[
    {  
        "keys": ["ctrl+alt+t"], "command": "terminus_open", "args": {
             "cmd": "python",
             "cwd": "${file_path:${folder}}",
             "panel_name": "python",
             "tag": "inksnw"
         }, "context": [
             { "key": "terminus_view", "operator": "not_equal", "operand": true }
         ]
     },
    { 
        "keys": ["ctrl+alt+t"], "command": "close", "context": [
            { "key": "terminus_view.tag", "operator": "equal", "operand": "inksnw"}
        ]
    }
]
```

**Comment by inksnw** [comment]
perfect!, now i can remove SublimeREPL
