### ISSUE TITLE
Possible bug? Can't erase any text

### ISSUE THREAD

**Issue by NoakPalander** [randy3k/Terminus#153]
The title is quite self explanatory, terminus completely ignores the backspace key. I'm not able to erase anything at all.

**Comment by randy3k** [comment]
Did you bind the backspace to any command?

**Comment by NoakPalander** [comment]
No, all settings are defaulted.

**Comment by randy3k** [comment]
With only limited information, I cannot provide any help. I recommend you to check if there is a package blinding the backspace key.
