### ISSUE TITLE
alt+7 in mac returns (arg: 7) 

### ISSUE THREAD

**Issue by Homap** [randy3k/Terminus#157]
Hello,

I'm using Terminus on sublime 3. Everything worked fine. Until some days ago, when I wanted to use pipe by typing `alt+7`, instead of pipe, I get `(arg: 7)`. alt key does not work anymore. I uninstalled sublime 3 and installed it again and still have the same problem. How could I solve this?

Thank you,
Homa

**Comment by randy3k** [comment]
What platform are you in? What is `alt+7` by the way? Do you have a special keyboard?

**Comment by Homap** [comment]
Hi,

I'm in Mac OS. I use a keyboard with Swedish language setting. When I want
to get pipe, I always take the alt key together with number 7. Now only in
terminus it has stopped workiing.

Best,
Homa

**Comment by randy3k** [comment]
`alt+7` was sent as literally as `meta+7` in default. For special layout keyboard, user may need to define the special keystrokes

```
    { "keys": ["alt+7"], "command": "terminus_keypress", "args": {"key": "|"}, "context": [{"key": "terminus_view"}] },
```

**Comment by Homap** [comment]
Thank you very much for your help. Could you please let me know how I could
add this command to sublime text?

Thanks!

**Comment by Afrowave** [comment]
In Sublime Text, type in `cmd + shift+ p` and then type the word, `keys`.

Put the instructions given by @randy3k in between the square brackets of the "Default(OSX).sublime-keymap" file.

**Comment by Homap** [comment]
Thank you so much! It is working great now!
