### ISSUE TITLE
Could use git-bash on windows?

### ISSUE THREAD

**Issue by chun-chun** [randy3k/Terminus#163]
It is possible could open terminus with git-bash in sublime view.

**Comment by randy3k** [comment]
The simple answer is yes. The exact answer depends  on your setup. I can’t provide any help without further details. You might want to look at some of the old issues.

**Comment by chun-chun** [comment]
Thank you for your reply. According to your suggestion, I refer to issue #56. I tried to use the sh.exe of the bin file instead of git-bash.exe. It can really help me with this problem without opening another command line window.

**Comment by esyede** [comment]
This is my (working) config for git bash, I don't know if it's the correct way or not but it works for me:

```json
{
    "default_config": {
        "linux": null,
        "osx": null,
        "windows": "git-bash", // must be identical with the shell config name
    },
    "shell_configs": [
        {
            "name": "git-bash", // i mean, this one
            "cmd": ["D:/Laragon/bin/git/bin/bash.exe"], // you need to adjust this too
            "env": {},
            "enable": true,
            "default": true,
            "platforms": ["windows"],
        }
    ],
    "theme": "darkside",
}
```



<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/19880d54-f3a3-474d-af05-1bff8263b5f0" />
