### ISSUE TITLE
Palenight theme?

### ISSUE THREAD

**Issue by danilofreire** [randy3k/Terminus#164]
Hi! Thanks very much for your work! I've been using a lot of your packages, such as `Terminus`, `radian`, and `SendCode`. They're awesome!

I would like to kindly ask you if you plan the include a version of [Palenight](https://github.com/JonathanSpeek/palenight-iterm2), a variation of the [Material theme](https://github.com/equinusocio/material-theme). I think it looks great and maybe others like it too! Many thanks 😃

**Comment by randy3k** [comment]
Please remind that you could always set your own theme by defining the colors in the preference.

**Comment by danilofreire** [comment]
Many thanks for your reply. I will do so!
