### ISSUE TITLE
How to change color of file folder

### ISSUE THREAD

**Issue by kevinli1224** [randy3k/Terminus#165]
Dear Sir
When I run "ls"  at terminus, some file folder's color is blue, such as  "Documents" and "Downloads" folder as below , but it is very vague, how  to change this color? Thanks

![Screenshot from 2019-11-07 09:53:43](https://user-images.githubusercontent.com/57401271/68353470-ad974f80-0144-11ea-9025-26c626c18a63.png)

**Comment by randy3k** [comment]
You could change the theme by using `Terminus Utilities: Select Theme`

**Comment by kevinli1224** [comment]
Randy3k,
I am new for terminus, I do not quite understand how to run "Terminus Utilities: Select Theme", can you tell me how to run it one by one step? Thanks you.

**Comment by randy3k** [comment]
Open command palette by using <kbd>Ctrl+Shift+P</kbd> (Windows/Linux) or <kbd>Cmd+Shift+P</kbd> (mac); then search for `Terminus Utilities: Select Theme` and hit enter.

**Comment by kevinli1224** [comment]
Now it works, thanks you !

**Comment by Annihilation7** [comment]
but it doesn' work for me, my system is macOS...
