### ISSUE TITLE
Cannot Open Default Shell in Panel or View

### ISSUE THREAD

**Issue by crdob** [randy3k/Terminus#166]
I have been using Terminus for a long time without any problems. All of a sudden, Terminus stopped working. I am no longer able to open a default shell in panel or view. Specifically, CMD + Shift + P and "Terminus: Open Default Shell in Panel" does not do anything. Any help would be appreciated!

**Comment by randy3k** [comment]
Try reinstalling it, there is a gitch in the previous release.

**Comment by pochedls** [comment]
I had the same issue this morning (error below). 

Just wanted to note that uninstalling and reinstalling terminus worked for me. Thanks!

> Traceback (most recent call last):
>   File "/Users/uname/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/core.py", line 101, in <lambda>
>     sublime.set_timeout_async(lambda: self.run_async(**kwargs))
>   File "/Users/uname/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/core.py", line 132, in run_async
>     config = self.get_config_by_name("Default")
>   File "/Users/uname/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/core.py", line 298, in get_config_by_name
>     default_config = self.default_config()
>   File "/Users/uname/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/core.py", line 344, in default_config
>     if default_config_name.lower() == config["name"].lower():
> AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by crdob** [comment]
That fixed the issue. Thank you!
