### ISSUE TITLE
Other command not being recognize

### ISSUE THREAD

**Issue by losewin** [randy3k/Terminus#168]
Im using git bash on windows but still either on cmd.exe the other command is unrecognize such as npm which is needed.
When I tried it on the usual git-bash the command are working
![tKfh472](https://user-images.githubusercontent.com/14087762/69298108-dee54480-0c47-11ea-8df9-156db8527ecb.png)

But when I tried it on terminus
![Capture](https://user-images.githubusercontent.com/14087762/69298069-bfe6b280-0c47-11ea-9007-ee41f47f508c.PNG)

What might wrong with this? is this still part of the Terminus package?

**Comment by randy3k** [comment]
I assume that you'll need a login shell.

**Comment by losewin** [comment]
Ohh, thanks for the quick response. Didn't expect that, Hmm, what should I do, or is there a way to configure git-bash in terminus to login?

**Comment by losewin** [comment]
In my own case the only fix is to restart your PC, I guess this happens before `node` and `gulp` are newly installed.
