### ISSUE TITLE
shortcut not working

### ISSUE THREAD

**Issue by MadhavChoudhary** [randy3k/Terminus#169]
I have set a shortcut `cmd+delete` which sends hex code `0x15`, to delete the complete line till now in the prompt. I set this up in iTerm profile. When I installed terminus as a sublime package, all other shortcuts work as expected, the look is also completely the same, but this shortcut is not working. 
This is really important for me. Can anybody help on where and how to set this?

**Comment by randy3k** [comment]
I believe what you need is `ctrl+u`. Check the keyblindings to see how to map `super+delete` to `ctrl+u`

**Comment by MadhavChoudhary** [comment]
`ctrl+u` seems to be working. 
I am having this keybinding for terminus, but still `cmd+delete` isn't working.
```
[
    //Open a terminal view at current file directory
    {
        "keys": ["alt+`"], "command": "toggle_terminus_panel", "args": {
            "cwd": "${file_path:${folder}}"
        }
    },
        
    { "keys": ["super+delete"], "command": "terminus_keypress", "args": {
    		"key": "u", "ctrl": true
    	}, 

    	"context": [{"key": "terminus_view"}]	
    }   	
]
```

Am I doing something wrong?

**Comment by randy3k** [comment]
Ai, should it be `super+backspace`?

**Comment by MadhavChoudhary** [comment]
YESSS. Got it. Thanks.
Awesome package 👍

**Comment by randy3k** [comment]
Welcome.
