### ISSUE TITLE
Toggle panel to show running build panel

### ISSUE THREAD

**Issue by distefam** [randy3k/Terminus#170]
I wrote a custom `.sublime-build` file to run Expo builds, which works great. I also mapped ``alt+` ``  to `toggle_terminus_panel`. When I begin a build I'd like to hide its panel while working and be able to bring it back up with `toggle_terminus_panel` but doing so brings up a new panel altogether rather than toggling the existing one used by the build system. 

Is there any way to check if there is a build panel and toggle that one, otherwise bring up a new one?

Thank you for the fantastic plugin by the way!

For reference, my `expo.sublime-build` file is as follows:
```json
{
	"keyfiles": ["App.js"],
	"target": "terminus_exec",
	"cancel": "terminus_cancel_build",
	"shell_cmd": "expo start",
	"working_dir": "$folder"
}

```

**Comment by randy3k** [comment]
`toggle_terminus_panel` doesn't work with Terminus Build Results.

You would either use the mouse to click the lower-left icon and open the Terminus Build Result or consider the following keybinding to bring up the panel "Terminus Build Results",
```
{
    "keys": ["ctrl+alt+t"], "command": "show_panel", "args": {
        "panel": "output.Terminus Build Results"
    }
}
```

**Comment by randy3k** [comment]
In Sublime Text 4, there is a keybind `shift+escape` to display the default Build Results panel.

To better integrate with this keybind. In the latest Terminus release v0.3.5:

- If there is no panel visible, `shift+escape` would show the Terminus Build Results if it exists or it would show the default Build Results if it exists.
- If the Terminus Build Results panel is visible, then `shift+escape` will bring you back to the default Build Results if it exists.
