### ISSUE TITLE
Default settings do not appear

### ISSUE THREAD

**Issue by jh-min** [randy3k/Terminus#171]
<img width="960" alt="whynotappear" src="https://user-images.githubusercontent.com/57447828/70612675-b5b64380-1c4a-11ea-905f-84c2490dac81.PNG">
Preferences: Terminus Settings/Command Palette/Key Bindings all display empty tab in left (I am using Windows 10).
Thank you in advance!

**Comment by randy3k** [comment]
You might have accidentally removed the default settings. Try reinstalling it.

**Comment by jh-min** [comment]
@randy3k I reinstalled it (and rebooted the OS) but still see nothing on the left tab...

**Comment by randy3k** [comment]
I am not sure. But there is one thing which catchs my eyes, I see the slashes of the path in the title are now crossout w's.

**Comment by SteVader** [comment]
I can confirm that I am experiencing the same issue on a clean first time install. Windows 10, ST3. Have also tried reinstalling the package and rebooting OS to no avail.

**Comment by SteVader** [comment]
Further to this I have just reset Sublime Text back to default settings by removing %APPDATA%/Sublime Text 3/ folder. Uninstalled Sublime Text 3 and removed C:\Program Files\Sublime Text 3\ folder before rebooting and reinstalling a clean version of Sublime Text 3 (v3.2.2 Build 3211). I entered my license, installed package control followed by the Terminus package. Restarted ST3 and opened Preferences > Package Settings > Terminus > Settings...

![Sublime Text 3_Packages_User_Terminus sublime-set](https://user-images.githubusercontent.com/2436007/70996901-ab24ff80-20cb-11ea-99cb-b02afe1ad778.png)

**Comment by randy3k** [comment]
Thank you for testing. I am able to reproduce it and it should be fixed in the coming v0.3.6.

**Comment by SteVader** [comment]
That’s excellent, thanks.
