### ISSUE TITLE
need help with trim_history

### ISSUE THREAD

**Issue by arcturus140** [randy3k/Terminus#172]
My build on Terminus Shell in View currently does not show the complete output. Reading other issues here I think the setting `trim_history` can be used to change the size of build history. 

My settings are: 
**Terminus.sublime-settings - User**
```
{
	"trim_history": 10
}
```

How does this setting work? Is this setting expected to showing 10 lines of build output in the View?

**Comment by randy3k** [comment]
What do you mean when you say "does not show the complete output"?

There is a setting called `scrollback_history_size`, but that's not relevant here.

**Comment by arcturus140** [comment]
I mean that I am running a build with Terminus: Open Default Shell in View. In the tab I can see the build log. After the build finished only 500 lines are shown. When I scroll up to the first line in the tab The lines before are missing.

**Comment by randy3k** [comment]
The default `scrollback_history_size` is 10000, it might trim the history down to 10% of it (i.e., 1000 lines) if number of lines is great than that. 500 seems a strange number to me.

How many lines are you expecting?

**Comment by arcturus140** [comment]
You are right it was 7200 lines not 500. I set `scrollback_history_size` to 50000 and the complete build output is shown. 

The complete build has ~29k lines. 

`scrollback_history_size` is what I was looking for, it works great. Thank you!

I still don't understand what is the purpose of `trim_history`?

**Comment by randy3k** [comment]
If one creates an infinite loop of writing something to the terminal, the limit will avoid the terminal to grow indefinitely.

**Comment by arcturus140** [comment]
So `trim_history` removes the percentage of lines of `scrollback_history_size` from the View?

I set `scrollback_history_size` to `30000` and `trim_history`; once to 10 and once to 90. 

In both cases I got the lower `18209` lines of output. Without `trim_history` I get the total build which is `28710` lines.

**Comment by randy3k** [comment]
There is no setting called `trim_history`. We remove 10% of the lines from the top if the terminal hits the limit.
