### ISSUE TITLE
focus back terminus in panel

### ISSUE THREAD

**Issue by jgirardet** [randy3k/Terminus#18]
If the lost focus, there is no way to go back to it. for example you loose your current ipython "session".
new panel close the current panel.

the idea would be  for new panel command :
```python
if  "output.Terminal" in window.panels:
   window.run_command("show_panel", args={"panel":"output.Terminus"})
else:
  window.run_commad("terminus_open", args={"config_name": "Default", "panel_name": "Terminus"})
```

i'll do the pr if you want
great plugin anyway
Jimmy

**Comment by randy3k** [comment]
It could be done by the `toggle_terminus_panel` command.

https://github.com/randy3k/Terminus#user-key-bindings

**Comment by jgirardet** [comment]
oh sorry I missed it
