### ISSUE TITLE
terminus fails to open R

### ISSUE THREAD

**Issue by JanaJarecki** [randy3k/Terminus#181]
Hi there,
I am on windows 10, since today, terminus fails to open the R console. I haven't changed any of the settings (and I also don't see a push of new code here). Any idea what could have happened?

My terminus preferences for R are

{
			"cmd": "........R-3.6.1patched\\bin\\x64\\R.exe",
			"default": true,
			"enable": true,
			"env":
			{
			},
			"name": "R",
			"platforms":
			[
				"windows"
			]
		}

**Comment by JanaJarecki** [comment]
Nevermind, it seems you updated the format for the cmd to use square brackets around the command cmd entry

`"cmd": ["C:\\Program Files\\R\\R-3.6.1patched\\bin\\x64\\R.exe"],`

hope it helps anybody in the future

J

**Comment by randy3k** [comment]
Well, I didn't expect the update will break this. Let me double check the code.

**Comment by randy3k** [comment]
v0.3.11 should fix the bug. Thank you for raising it.
