### ISSUE TITLE
Terminus not in package control

### ISSUE THREAD

**Issue by 211217613** [randy3k/Terminus#185]
I open up package control: install then type terminus and nothing comes up.

**Comment by ibrahimnkya** [comment]
I also tried to open install it in my arch linux but nothing comes up

**Comment by randy3k** [comment]
It doesn't show any error in package control website.
https://packagecontrol.io/packages/Terminus
and
Terminus repo is also in https://packagecontrol.io/channel_v3.json

My only advice is to try again...

**Comment by ibrahimnkya** [comment]
thank you so much i gave it a try and its working quite well

**Comment by 211217613** [comment]
Ok I had terminus in the `disabled package` list of package control. That's why it wasn't showing up.

:man_facepalming:
