### ISSUE TITLE
The command line background is inexplicably white

### ISSUE THREAD

**Issue by Brolly0204** [randy3k/Terminus#187]
![1581151123508](https://user-images.githubusercontent.com/16096724/74082102-8fb5ef80-4a91-11ea-893b-b44214d40aa9.jpg)

**Comment by Brolly0204** [comment]
I found it was caused by the installation of TrailingSpaces

**Comment by randy3k** [comment]
You will need to disable TrailingSpaces in Terminus.

**Comment by Brolly0204** [comment]
ok
