### ISSUE TITLE
Killing running command

### ISSUE THREAD

**Issue by choallin** [randy3k/Terminus#188]
I would like to use the terminus terminal to run my dockerized app.
I start my project in the terminal with `docker-compose up` and it starts the rails app + all the dependencies as it should. But at the end of the coding session or when switching to another project I want to kill the running process with ctrl+c and this is not working.   
I checked the settings and I changed the "natural_keyboard" setting to false but noting changed - I even restarted my sublime text instance just to make sure.

Is this a known limitation or am I missing something?

**Comment by randy3k** [comment]
What OS are you using? `ctrl+c` should work out of the box unless you have blinded it to something else.  Try to log running commands by `sublime.log_commands(True)`

**Comment by choallin** [comment]
I found the problem. Another plugin (Clipboard Manager) interfered with the shortcut... . I changed it there and now it is working :+1:

**Comment by randy3k** [comment]
Great.
