### ISSUE TITLE
Terminus and Python / conda virtual environments

### ISSUE THREAD

**Issue by andykmiles** [randy3k/Terminus#189]
Is it possible to have Terminus automatically activate python and / or conda virtual environments automatically? Ideally on Windows as well as Linux.

**Comment by randy3k** [comment]
In your .bashrc, just put

```
if [ "$TERM_PROGRAM" == "Terminus-Sublime" ]; then
    conda activate your_environment
fi
```

**Comment by KristoforMaynard** [comment]
@pythonsavvy, I put together a plugin that nearly does what you're looking for: [TerminusAddons](https://github.com/KristoforMaynard/TerminusAddons). It comes with a build system to run scripts (or make) in Terminus, and if a setting called "conda_env" is set in your preferences, it automatically activates a conda environment. It also launches python scripts with pipenv if it sees a Pipfile in a parent directory. The advantage to this approach over using bashrc is it can be set per-project.

**Comment by andykmiles** [comment]
Thank you for this. Using it now!

**Comment by mrrezaie** [comment]
> In your .bashrc, just put

> if [ "$TERM_PROGRAM" == "Terminus-Sublime" ]; then
    conda activate your_environment
fi

@randy3k Hi, how can I do this in Windows? Is `cmd` or `shell_cmd` able to first activate a conda env and then run ipython?

Thank you
