### ISSUE TITLE
.bashrc is not used

### ISSUE THREAD

**Issue by jgirardet** [randy3k/Terminus#19]
Hi,
running `"command": "terminus_open", "args": {"config_name": "Bash", "panel_name": "Terminus"}`
launch a terminus terminal with bash but .bashrc is not taken in account since some env variable declared in are not present inside terminus.
If I run  `bash` inside terminus, it solves the problem

**Comment by randy3k** [comment]
Terminus opens login shells. So it is likely that you didn't set your bash_profile correctly. Check this https://askubuntu.com/questions/161249/bashrc-not-executed-when-opening-new-terminal

**Comment by jgirardet** [comment]
indeed, my bash_profile was empty.
thanks
