### ISSUE TITLE
can't show the unicode symbol with color

### ISSUE THREAD

**Issue by jaredyam** [randy3k/Terminus#191]
I am using a colorized Unicode symbol as my terminal indicator, which shows the feedback about the last command. In the terminus shell, the symbol shows ugly with an unexpected white background. Here are the screenshots:
<img width="762" alt="Screen Shot 2020-02-18 at 10 08 42 AM" src="https://user-images.githubusercontent.com/50312506/74698420-abab5500-5238-11ea-8233-3bc7895dd447.png">
<img width="360" alt="Screen Shot 2020-02-18 at 10 09 05 AM" src="https://user-images.githubusercontent.com/50312506/74698422-aea64580-5238-11ea-9ea7-6b835a033030.png">

Is this an issue same with #75 ? Can I improve the terminus look without rewriting my terminal's config?
[I have tried 256color=true and vscode terminal shows it well.]

**Comment by randy3k** [comment]
What unicode is that char? I don't have any issues here
<img width="496" alt="Screen Shot 2020-02-17 at 8 22 38 PM" src="https://user-images.githubusercontent.com/1690993/74703818-51bc7800-51c3-11ea-9675-8ca0ad9a34ce.png">

**Comment by jaredyam** [comment]
@randy3k \u203d ‽

**Comment by randy3k** [comment]
By the way, did you change `"unix_term"` to  `"xterm-256color"`.

**Comment by jaredyam** [comment]
Here is my setting:
<img width="434" alt="Screen Shot 2020-02-18 at 1 25 07 PM" src="https://user-images.githubusercontent.com/50312506/74706814-eae69f80-5252-11ea-8f61-c95db2b48669.png">
and I have tried the code you refers It seems work for me.
<img width="405" alt="Screen Shot 2020-02-18 at 1 32 58 PM" src="https://user-images.githubusercontent.com/50312506/74706911-36994900-5253-11ea-9d42-a178cd5428ba.png">
Does it my zsh theme's problem? I am using the `spaceship`  zsh theme, the configs for my indicator using the below codes in zsh:
```bash
ZSH_THEME="spaceship"
SPACESHIP_CHAR_SYMBOL=(" \u003f ")
SPACESHIP_CHAR_COLOR_SUCCESS=("#fcd947")
SPACESHIP_CHAR_COLOR_FAILURE=("#f32525")
```
Why it not works in terminus, can I fix it?

**Comment by randy3k** [comment]
Could you turn on the debug mode and report what you see in the console?

**Comment by jaredyam** [comment]
Are these infomation useful?
```bash
DEBUG:Terminus:mode: [7, 25], cursor: 0.0
receieved: 
[0m[27m[24m[J[1m[0m[1m[36m~[0m[36m[39m[1m [0m
[1m🌈💛🧡💜[0m[1m[38;2;252;217;71m ‽ [0m[38;2;252;217;71m[39m[1m[0m[K[?1h=[?2004h
DEBUG:Terminus:receieved: 
[0m[27m[24m[J[1m[0m[1m[36m~[0m[36m[39m[1m [0m
[1m🌈💛🧡💜[0m[1m[38;2;252;217;71m ‽ [0m[38;2;252;217;71m[39m[1m[0m[K[?1h=[?2004h
add 0 line(s) to scroll back history
```

**Comment by randy3k** [comment]
`38;2;252;217;71` is a 24 bit color not 256 bit which is not supported in Terminus. I think it is related to color in `SPACESHIP_CHAR_COLOR_SUCCESS` and `SPACESHIP_CHAR_COLOR_FAILURE`.

**Comment by jaredyam** [comment]
Oh, I have changed the color into 8-bit encode, terminus works for now! Thank for your help!

**Comment by jaredyam** [comment]
Can more colors be supported in the future? Since I tried some simple colors for testing, it seems that only some very simple colors supported for now (red, yellow, blue...) not 8 bit.

**Comment by randy3k** [comment]
Terminus does support all 8bit colors. Did you find any 8-bit color not working?

In theory, 24bit color could be supported, BUT it will decrease the performance by a lot as we are relying on a hack to display different colors in Sublime Text.

**Comment by jaredyam** [comment]
I tried some colors on this [web](https://www.rapidtables.com/web/color/RGB_Color.html) before, color encoded with combining 0 and 255 just works for me. i.e these:
<img width="526" alt="Screen Shot 2020-02-18 at 3 50 23 PM" src="https://user-images.githubusercontent.com/50312506/74714883-6bfb6200-5266-11ea-8ef1-f59b09495732.png">
Others do not work. Actually these colors can be enough but I'll appreciate it if more colors could be supported.

**Comment by jaredyam** [comment]
An unessential report:
![256colour](https://user-images.githubusercontent.com/50312506/74716924-6869da00-526a-11ea-824c-e6155e8de513.png)
This 256 colormap not all works for me. A brave assumption is that just below colors can show successively::
<img width="526" alt="Screen Shot 2020-02-18 at 3 50 23 PM" src="https://user-images.githubusercontent.com/50312506/74717388-458bf580-526b-11ea-8e18-f977c6c67634.png">
or
```bash
        // "00": "#000000",  // black
        // "01": "#cd0000",  // red
        // "02": "#00cd00",  // green
        // "03": "#cdcd00",  // brown
        // "04": "#0000ee",  // blue
        // "05": "#cd00cd",  // magenta
        // "06": "#00cdcd",  // cyan
        // "07": "#e5e5e5",  // white
        // "08": "#7f7f7f",  // light_black
        // "09": "#ff0000",  // light_red
        // "10": "#00ff00",  // light_green
        // "11": "#ffff00",  // light_brown
        // "12": "#5c5cff",  // light_blue
        // "13": "#ff00ff",  // light_magenta
        // "14": "#00ffff",  // light_cyan
        // "15": "#ffffff"   // light_white
```
in the terminus setting.

**Comment by randy3k** [comment]
I am not sure what you meant. What is not working for you?

**Comment by jaredyam** [comment]
I made a mistake before, the issue has been fixed. The 8-bit color works well.
