### ISSUE TITLE
Terminus cannot run npm commands

### ISSUE THREAD

**Issue by candreslobor** [randy3k/Terminus#194]
i've installed some packages globally with npm, all these packages are in my ~/.node-global directory. The thing is this, i've added an `export PATH="$PATH:$HOME/.npm-global/bin"` to the .bashrc config file to run my commands from console.

Right now when i try to run `node-sass` from terminus over sublime-text3 it says:
`bash: node-sass: command not found` like it isn't reading the .bashrc

Solved. you only need to add the same export path to ~/.profile file. Hope it be helpful

**Comment by randy3k** [comment]
What OS are you using?

**Comment by candreslobor** [comment]
Linux Solus Budgie 4.1

**Comment by candreslobor** [comment]
> What OS are you using?

**Comment by randy3k** [comment]
Perhaps it’s os dependent issue. Afaik, Ubuntu will happily read `.bashrc`
