### ISSUE TITLE
[Feature request] Split view/multiple panes

### ISSUE THREAD

**Issue by chrispetrou** [randy3k/Terminus#196]
Hi @randy3k ! First of all I'd like to thank you (_and all the contributors of course_) for this amazing sublime text plugin. I found out about it recently and I find it extremely useful. So I'd like to ask is there is any way to have two terminal sessions opened in two separate panels.

To be more clear is there a way to replicate VS code's functionality shown below:

![1](https://user-images.githubusercontent.com/36112975/75199621-3bd32800-576c-11ea-8cd3-6eed0a570e5e.png)

Either e.g. using split view or through a dropdown etc...? I read the documentation and also tried through settings but had no luck so far!

**Comment by randy3k** [comment]
<img width="252" alt="Screen Shot 2020-02-24 at 3 32 36 PM" src="https://user-images.githubusercontent.com/1690993/75200588-e6baf600-571a-11ea-8850-482b700556b9.png">


It is right at the lower left corner.

**Comment by chrispetrou** [comment]
Thanks for the response - that's indeed useful info, but how do you actually have all those terminals opened in the first place? I must be missing something here, I tried all the combinations with _option+control+t etc.._. but nothing worked so far (_I'm on a mac btw_).

**Comment by randy3k** [comment]
Terminus doesn't define any keybindings. You could, for example, define

```
    {
        "keys": ["super+shift+t"], "command": "terminus_open",
        "args": {
            "cwd": "$file_path",
			"panel_name": "Terminus"
        }
    }
```

Note: "Terminus" is the only panel name that allows `Terminus`, `Terminus 2` etc. Other value of `panel_name` would kill any existing terminal with the same name.

**Comment by chrispetrou** [comment]
Thank you very much! That's exactly what I was looking for!

**Comment by alevroub** [comment]
> Note: "Terminus" is the only panel name that allows Terminus, Terminus 2 etc. Other value of panel_name would kill any existing terminal with the same name.

@randy3k Is there a particular reason for this? `available_panel_name` is still checking for existing names and appending an index to the duplicate, so whether the name is the default one or passed as an argument to `terminal_open` shouldn't make a difference, and would make the function more practical overall.
