### ISSUE TITLE
Terminus as build system: go to next result

### ISSUE THREAD

**Issue by nsubiron** [randy3k/Terminus#198]
Using Terminus as target for a build system, all seems to be working fine except that the shortcuts for next result are not working until I click the output panel. Once clicked it works as expected.

**Comment by randy3k** [comment]
It needs some tweaks in order to get it works seamlessly.

**Comment by nsubiron** [comment]
what sort of tweaks? inside Terminus or something in my configuration? anything I could help with?

**Comment by randy3k** [comment]
771f0a9 has fixed it.

**Comment by nsubiron** [comment]
It works, thanks a lot :)
