### ISSUE TITLE
Input error in Chinese input method 

### ISSUE THREAD

**Issue by inksnw** [randy3k/Terminus#20]
![_2018_07_10_09_52_22_492](https://user-images.githubusercontent.com/17754890/42484813-5db500d4-8427-11e8-8136-f023c4a83655.gif)

when try to input a word like '相信' but  it is turned into '相相信',single word works fine

**Comment by randy3k** [comment]
thanks for the report. I could reproduce it. Detecting non-ASCII input is actually built on top of a hack. We might need to a different hack to detect the input.

**Comment by randy3k** [comment]
should be fixed by de95120

**Comment by inksnw** [comment]
It worked!

**Comment by randy3k** [comment]
I have a problem of using arrows (left/right) to choose words on macOS. Do you experience the same on Windows? (I am guessing that you are using Windows)

**Comment by inksnw** [comment]
![_2018_07_10_15_54_10_614](https://user-images.githubusercontent.com/17754890/42496742-9acf4efc-8459-11e8-985b-76aceca46ec2.gif)
you mean shift+left/right? yes,it becomes "DDDDDD"

**Comment by randy3k** [comment]
No, I meant choosing between the prompt texts, eg 相信 and 相念

**Comment by inksnw** [comment]
I usually use ; and ' or 1,2,3 to choose  prompt texts, it works fine .
Try to use left/right and up/down to select  prompt texts ,when i press Enter nothing come

**Comment by randy3k** [comment]
Ai...it is hard to fix the arrow issue. I guess I would just mark it as wont't fix for niw.

**Comment by iorippi** [comment]
@randy3k 
Seems to me as though arrow keys are working perfectly on Windows10 (though I use Chinese so I don't know if the same problem applies to my situation)
