### ISSUE TITLE
Switch focus between tab and terminus panel.

### ISSUE THREAD

**Issue by karan173** [randy3k/Terminus#202]
Hi, I am using the [alt + `] keybinding to open the terminus panel. This also switches focus to the panel. Is there a keybinding I can set up to move the focus back to the active tab while still keeping the terminal panel open?

**Comment by randy3k** [comment]
If you have just one pane, you could use `Ctrl+K`, `Ctrl+K` (`Cmd+K`, `Cmd+K` for mac). 

Closing it because it is not actually a Terminus related issue.
