### ISSUE TITLE
Make http(s) URLs links

### ISSUE THREAD

**Issue by jkfran** [randy3k/Terminus#206]
I am not sure if this is possible or not but I would be nice to make URLs in the output clickables.

**Comment by randy3k** [comment]
The links are not clickable directly, but a button should pop up if you hover a link.

**Comment by jkfran** [comment]
@randy3k Oh, you are right! I didn't wait to see it. It would be nice to have also the ctrl + click to make it faster.

**Comment by randy3k** [comment]
Unfortunately, Sublime API doesn’t support ctrl+click directly. It’s the reason I made the button. You could also right click a link and click on the url in the menu.

**Comment by jkfran** [comment]
Okay, I am going to close it then.

Thank you!
