### ISSUE TITLE
Customizing the theme for Diff input and output colors 

### ISSUE THREAD

**Issue by prabh1601** [randy3k/Terminus#213]
I use terminus with Sublime text for cpp files .. Now one thing that bothers me is that all my input and output are of same color and it really puts it hard to distinguish that what is input and what is output ...
So is there a way to get this thing done ... lets say screen shows me output of "hello world" and input is "12" .. So briefly I want these two be of diff colors

**Comment by randy3k** [comment]
Why don't you print with colors in the first place?

**Comment by prabh1601** [comment]
I am a competitive programmer buddy ... Ain't much feasible for me if  i start doing so

**Comment by randy3k** [comment]
Anyhow, it is the duty of the program or process to handle colors, not ours.
