### ISSUE TITLE
Theme doesn't change

### ISSUE THREAD

**Issue by itsyourOOP** [randy3k/Terminus#216]
Whenever I choose a theme for Terminus, it doesn't actually change colors. It's like it's stuck. 
[Pastebin of settings if needed](https://pastebin.com/mb7L6Rne)

On Archlinux

**Comment by monkape** [comment]
Have you restarted Sublime?

**Comment by itsyourOOP** [comment]
That did fix it, and I'm kinda embarrassed that I didn't think of that. Thanks.
