### ISSUE TITLE
[OSX] Causes mouse cursor to blink (change shape) in whole system

### ISSUE THREAD

**Issue by rchl** [randy3k/Terminus#219]
Terminus, or maybe rather shell within Terminus, sometimes causes the mouse cursor to flicker in the whole OS. This doesn't happen immediately and opening Terminus panel is not enough to reproduce it. It usually happens after some time of using Terminus. Maybe after triggering specific commands in the shell. I haven't pinned that down yet.

Here is a recording of this happening:
![Screen Recording 2020-06-02 at 20 48 32](https://user-images.githubusercontent.com/153197/83558657-a20dda80-a513-11ea-8c56-47af51f06e0d.gif)

Once I've killed the ZSH process started by Terminus, the mouse becomes steady. Then I open new Terminus panel and it starts doing that again.

I'm also using ZSH in iTerm heavily and never have the same issue triggering within ZSH started in iTerm.

I'm on macOS 10.15.

**Comment by randy3k** [comment]
I remember seeing similar things on other occasions than Sublime Text, not sure how to reproduce it though.

**Comment by rchl** [comment]
This was an [ST issue](https://github.com/sublimehq/sublime_text/issues/3331) and is fixed in ST4
