### ISSUE TITLE
Error loading Terminus theme

### ISSUE THREAD

**Issue by Cezear** [randy3k/Terminus#22]
Just installed and tried opening it, everything seems to work perfectly fine besides the theme doesn't load.

![terminus](https://user-images.githubusercontent.com/25166787/42584212-ab2725e8-8500-11e8-976c-522590c1e8c7.PNG)

**Comment by randy3k** [comment]
That’s strange. What version of SublimeText are you using?

**Comment by RyanJLockard** [comment]
Whelp, just updated to 3.1.1 Build 3176 and it's working fine

**Comment by randy3k** [comment]
I have set the minimum requirement of Sublime Text to 3160.

**Comment by Syncrossus** [comment]
I'm having the same issue on build 3211 on Manjaro.

**Comment by randy3k** [comment]
Try to restart Sublime text?

**Comment by Syncrossus** [comment]
I had already done that, and this persisted across software updates, computer restarts, and tweaking theme settings. I ended up uninstalling it and reinstalling it through Package Control, which made Sublime Text crash, but the issue seems to have worked itself out.

**Comment by randy3k** [comment]
Um....anyway, glad to hear that the issue is gone
