### ISSUE TITLE
settings don't apply on ubuntu 20.04

### ISSUE THREAD

**Issue by kurokirasama** [randy3k/Terminus#222]
hello,
I have sublime text with terminus extension on an ubuntu 18.04 machine with the following settings:

```
{
    "256color": true,
    "theme": "user",
    "unix_term": "xterm-256color",
    "user_theme_colors":
    {
        "background": "#000000",
        "caret": "#ffffff",
        "foreground": "#37ff00"
    },
    "viewsettings":
    {
        "font_face": "Ubuntu Regular"
    }
}
```
Now I just installed sublime and terminus in an ubuntu 20.04 machine, but these setting <sdoesn't seem to apply. Moreover, if I change any of the colors nothing happens on terminus.

What I'm doing wrong???

**Comment by randy3k** [comment]
The settings seem right. Try restarting Sublime?

**Comment by kurokirasama** [comment]
several times

**Comment by kurokirasama** [comment]
wth??? I just tried it again for the n time and it worked.... sorry for the trouble
