### ISSUE TITLE
Automatic Terminus theme

### ISSUE THREAD

**Issue by SyntaxErr0rr** [randy3k/Terminus#232]
This would be a very convenient feature considering that the given themes aren't the only ones used by developers. For example, I use a custom syntax theme and it would be nice if Terminus could somehow grab the the colors of that theme and set it as the color theme.

**Comment by monkape** [comment]
This would be a very nice addition, but I don't think it's that simple as scheme colours don't exactly map one-to-one to terminal colours.

**Comment by SyntaxErr0rr** [comment]
> This would be a very nice addition, but I don't think it's that simple as scheme colours don't exactly map one-to-one to terminal colours.

That's true. Thanks for the insight. I'll close this down.
