### ISSUE TITLE
Initial terminal output messed up.

### ISSUE THREAD

**Issue by deathaxe** [randy3k/Terminus#236]
When opening a new terminus pane, the initial output of the interpreter is messed up. It looks as the number of columns is heavily limited. 

Powershell

![grafik](https://user-images.githubusercontent.com/16542113/89038934-853e2980-d341-11ea-9379-8902f02a9c17.png)

Bash

![grafik](https://user-images.githubusercontent.com/16542113/89038479-b407d000-d340-11ea-9fef-2cd3699be2e9.png)

After hitting enter or simply run the first command, the with is ok.

I guess it is caused by or at least related with https://github.com/randy3k/Terminus/pull/215/files

- Windows 10 x64 2004
- Sublime Text 4079
- Terminus 0.3.16

**Comment by randy3k** [comment]
I don't think it's related to that PR. I have been seeing similar issue for sine time. It seems a synchronisation issue of the renderer after a size change and it does always occur.

**Comment by deathaxe** [comment]
The window size doesn't change when starting the terminal and I can reproduce 100% at each startup with each interpreter. I've never seen that before.

That said, I am not sure whether it is related with that PR, but why is the width limited to 20 characters, which is exactly the default value of `min_columns` setting?

The good news is I can workaround that bug by setting `"min_columns": 80`.

**Comment by randy3k** [comment]
Ah, you may be right. 

There is a fallback to 80 if the detected width is 0.
However the PR sets a minimum to 20 instead of 0 (the value that we get for a new panel) and it breaks the fallback.

**Comment by randy3k** [comment]
71e5acc should fix it. Please reopen if it doesn't.

**Comment by deathaxe** [comment]
Thanks.
