### ISSUE TITLE
Support for ColorLS

### ISSUE THREAD

**Issue by andremacola** [randy3k/Terminus#237]
Is it possible to add support for https://github.com/athityakumar/colorls ?

When using colorls this happens: 

![Captura de Tela 2020-08-09 às 19 09 12](https://user-images.githubusercontent.com/3408809/89742848-d5209d00-da73-11ea-8c05-5a0efbc9b00a.png)

**Comment by randy3k** [comment]
Did you turn on 256 colors?

**Comment by andremacola** [comment]
> Did you turn on 256 colors?

🤦‍♂️ Ops.. I'm sorry. Enabled and now is working.
