### ISSUE TITLE
Terminus Tab View steals cursor focus when running some npm scripts

### ISSUE THREAD

**Issue by elzii** [randy3k/Terminus#238]
Sample `package.json`

```json
{                                                                         
  "develop": "concurrently -r \"npm:type-check:watch\" \"npm:start\"",    
  "start": "parcel ./src/index.html",                                     
  "type-check:watch": "tsc --noEmit --watch"
} 
```

I have Terminus opened in a Tab View. If I make a change to my file when running the `type-check:watch` or `develop` commands, whenever I save the file, the cursor focus will switch to the Terminus tab. 

It does not happen when running `npm run start` however.

Here is the log output with `sublime.log_commands(True)` enabled:

## When running `npm run type-check:watch` and saving a file (PROBLEM):

```
command: lsp_save
command: save {"async": true}
command: unmark_undo_groups_for_gluing
command: terminus_render
command: terminus_show_cursor
command: terminus_reset
command: unmark_undo_groups_for_gluing
command: unmark_undo_groups_for_gluing
command: terminus_initialize
command: set_layout {"cells": [[0, 0, 1, 1], [1, 0, 2, 1]], "cols": [0.0, 0.521482180478, 1.0], "rows": [0.0, 1.0]}
command: terminus_render
command: terminus_show_cursor
```

## When running `npm run start` and saving a file (NO PROBLEM)

```
command: lsp_save
command: save {"async": true}
command: unmark_undo_groups_for_gluing
command: terminus_render
command: terminus_show_cursor
command: terminus_render
command: terminus_show_cursor
command: terminus_render
command: terminus_show_cursor
command: terminus_render
command: terminus_show_cursor
command: terminus_render
command: terminus_show_cursor
```

The obvious difference is that `terminus_reset` is being called, which has some `window.focus_view()` calls in it.

**Comment by elzii** [comment]
Update: This also happens in a panel view, not just tab

**Comment by mitranim** [comment]
Installed Terminus, instantly ran into this problem. This escape sequence is used for clearing the scrollback, and is commonly used by file-watching tools. It's extremely useful for seeing a "clean" result after every rerun, avoiding confusion with previous results. The focus stealing makes Terminus' tabs incompatible with such tools, and it's a shame. Suggestions would be very much appreciated.

**Comment by randy3k** [comment]
Oh, I just realized I have been ignoring this thread. I am on it now. Basically we need to have a version of `terminus_reset` that doesn't change focus.

**Comment by mitranim** [comment]
Whoah that was quick. Thanks!

**Comment by randy3k** [comment]
Thank you for bumping it up by the way .
