### ISSUE TITLE
My output is "ugly"

### ISSUE THREAD

**Issue by Khantanjil** [randy3k/Terminus#239]
I was expecting to get an result like that: ![](https://forum.sublimetext.com/uploads/default/original/3X/7/5/75315d178fe854558037e52fa6071e2962c79591.png)
It have beautiful colors and etc...
But i have this:
![](https://i.imgur.com/F3IO3pC.jpg)

I would like to have a more beautiful result instead of looking ugly.

**Comment by randy3k** [comment]
You just change the color theme. And maybe enable 256 color.

**Comment by Khantanjil** [comment]
How can i enable 256 color?

**Comment by randy3k** [comment]
In Terminus Preferences.

**Comment by Khantanjil** [comment]
Its weird, i cant modify the file, on sublime text 3, it says the settings file is located on `/home/tanjil/.config/sublime-text-3/Packages/Terminus/Terminus.sublime-settings` but if i go on this file path, i dont have "Terminus" Folder
![screen](https://user-images.githubusercontent.com/61469147/89894983-f350df00-dbd2-11ea-8834-072f27146d72.jpg)

**Comment by randy3k** [comment]
It is the right behavior. The file is virtual and read only.

**Comment by Khantanjil** [comment]
Its now more beautiful, i used the terminus utilities for selecting an theme on command pallete
