### ISSUE TITLE
No trace of Terminus on fresh Sublime install

### ISSUE THREAD

**Issue by brenthuisman** [randy3k/Terminus#24]
I installed the Terminus package through packagecontrol on a fresh Sublime. I can find no trace of Terminus after installation however. Nothing under any menu item, nor does the package appear under package preferences. The `` alt+` `` hotkey has no effect either. In the Sublime console I see one line regarding Terminus `reloading plugin Terminus.main`.

I run Sublime on Windows 7x64. If I can provide you with more details I will gladly do so.

**Comment by randy3k** [comment]
You’ll need to copy the keybind to your keybind settings. Otherwise, 
you can always open terminal from the command palette.

**Comment by brenthuisman** [comment]
Ah, the `Terminus` in `Preferences: Terminus Key Bindings` threw me off (I only see the `Key Bindings` item under `Preferences`).

Thanks, it works now! And thanks for the excellent plugin!
