### ISSUE TITLE
[Windows] Can't type in terminal

### ISSUE THREAD

**Issue by maliex4mix4** [randy3k/Terminus#240]
![Capture](https://user-images.githubusercontent.com/49034182/90302902-61cac100-dea1-11ea-8eb8-34a75fc7cf6f.PNG)

I can't type anything at all.

**Comment by monkape** [comment]
Most likely due to your keybinds - what is reported in Sublime's console after calling `sublime.log_commands(True)`?

**Comment by lauverityhill** [comment]
My "solution" was copy-pasting the entire "default" settings to the "user" settings.

**Comment by maliex4mix4** [comment]
Thanks guys it works now i don't know how it happened. But thanks though :+1:
