### ISSUE TITLE
How can i change the colors that i want?

### ISSUE THREAD

**Issue by tanjilk** [randy3k/Terminus#241]
![Screenshot from 2020-08-27 18-57-34](https://user-images.githubusercontent.com/47666341/91478115-41363a00-e897-11ea-9a8b-d162a2a89b4c.png)
I want to change the blue color to another color. How can i do it?

**Comment by randy3k** [comment]
You could customize the theme color or choose a predefined theme.

**Comment by tanjilk** [comment]
Thanks
