### ISSUE TITLE
Can't KeyboardInterrupt with ctrl+c in panel.

### ISSUE THREAD

**Issue by steventimberman** [randy3k/Terminus#243]
Running zshell in a panel (made with the ctrl-alt-t shortcut, except in panel), and the built in python build system activated. Unable to keyboard interrupt with ctrl+c, works in iterm. Have tried toying with the key bindings and system, and nothing has worked so far.

**Comment by randy3k** [comment]
would you enable the debug setting and report the log when `ctrl-c` is hit?

**Comment by steventimberman** [comment]
nothing is logged

**Comment by steventimberman** [comment]
Problem solved by setting config to Default
