### ISSUE TITLE
I can't see my powerline bash nor the zsh shell in terminus

### ISSUE THREAD

**Issue by vraxzeztan** [randy3k/Terminus#254]
Here is my zsh shell in terminal  - 

![Screenshot from 2020-11-10 23-49-57](https://user-images.githubusercontent.com/32648779/98715351-0761d380-23b0-11eb-8302-d57aec1a28c9.png)

Here is my bash shell in terminal - 
![Screenshot from 2020-11-10 23-55-19](https://user-images.githubusercontent.com/32648779/98715466-34ae8180-23b0-11eb-80bb-8ab4e41b7ebc.png)

Here is my bash shell in terminus - 
![Screenshot from 2020-11-10 23-55-51](https://user-images.githubusercontent.com/32648779/98715659-793a1d00-23b0-11eb-8425-a4b86f1b20b4.png)

Here is my zsh shell in terminus - 
![Screenshot from 2020-11-10 23-56-54](https://user-images.githubusercontent.com/32648779/98715696-8525df00-23b0-11eb-9a45-30e50537bf6d.png)

As shown I don't see anything when opening zsh in terminus and nor can I see the powerline of bash in terminus

Here are my settings - 
![Screenshot from 2020-11-10 23-58-42](https://user-images.githubusercontent.com/32648779/98715861-b4d4e700-23b0-11eb-862a-9ea4396e57ea.png)

Please help so that I can see similar shells in terminus.

**Comment by Afrowave** [comment]
hey @vraxzeztan,

Here is my set up. I am using Power10K but iwth Power9k settings. It took some time but I am happy with the results.

For Terminus, you don't need to duplicate the bash settings on the User side. Here are my settings, all on ZSH wit hTerminus, Terminal and Iterm respectively. 

![Screenshot 2020-11-10 at 22 24 38](https://user-images.githubusercontent.com/271274/98723887-03c84f80-23a4-11eb-8eef-694fd05cce51.png)

**Comment by vraxzeztan** [comment]
I too am using p10k , can you send your .zshrc or .p10k.sh file via pastebin, 
Maybe I have missed some export in them.

**Comment by Afrowave** [comment]
Here you go:
[Pastebin code](https://pastebin.com/HK9pT9eS)

**Comment by vraxzeztan** [comment]
I don't know why but for some reason it's not working for me, I'm using pop-os and you are using macOS maybe something else needs to be done for this.
