### ISSUE TITLE
Empty window when connecting with SSH

### ISSUE THREAD

**Issue by pzehner** [randy3k/Terminus#261]
I started a SSH connection to a remote server and the Terminus window went empty. Now, when I reopen Terminus, it tries to reestablish the connection and the window goes empty again.

Terminus version: 1.0.123
OS version: MS Windows 10 1809

**Comment by randy3k** [comment]
I think we will need a bit more information to identify the issue. Perhaps some screenshots?

**Comment by pzehner** [comment]
Wait, I made a confusion with https://github.com/Eugeny/terminus.
