### ISSUE TITLE
Doesn't print # character

### ISSUE THREAD

**Issue by mscwilson** [randy3k/Terminus#264]
Inputting # doesn't work. Perhaps this is a Mac UK keyboard thing where we have # on option+3 (because £ is on shift+3). Nothing shows up on pressing option+3, but then 3 copies of the next character pressed appear instead of one.

**Comment by randy3k** [comment]
It may be fixable by redefining the problematic keys in your user keybindings. Basically you will need to refine the `~` key with `alt + 3`.

**Comment by mscwilson** [comment]
Hi, thanks for your reply.
I'm not quite sure what change to make. I tried this and it didn't work, no # showed up (though it did stop the double extra characters appearing):
 `{ "keys": ["alt+3"], "command": "terminus_keypress", "args": {"key": "#", "alt": true}, "context": [{"key": "terminus_view"}] },`
 
 On the Mac keyboard the `~` is together with ` ` `, next to the left shift key. I have this line
`{ "keys": ["alt+`"], "command": "toggle_terminus_panel" }` in use already.

**Comment by randy3k** [comment]
I think you just need `"args": {"key": "#"}`

**Comment by mscwilson** [comment]
This worked! Thank you!
