### ISSUE TITLE
Terminus Not Functioning On Ubuntu Linux 

### ISSUE THREAD

**Issue by corinthian13** [randy3k/Terminus#269]
I have used Terminus within Windows Sublime Text and it has been generally successful.
However, it has never worked properly for me in Ubuntu 20.04.

1. No Terminal commands are visible on Package Control.
2. When CTRL+ALT+T are pressed, all that happens is that an Ubuntu terminal window opens at the /home/<username> folder.
3. It should open within a Sublime Text tab and within the same directory as that of the currently open tab.
![terminus-open-terminal-tab](https://user-images.githubusercontent.com/7750275/112153017-c76ef080-8bda-11eb-8aca-5269064dc241.png)

**Comment by randy3k** [comment]
I guess it is just because your system has stolen the key combination. Please try a different key combination.

**Comment by corinthian13** [comment]
Key combination ? 
What do you mean ?
I just installed a plugin for Sublime Text into my Ubuntu 20.04 PC. I had no hand, act or part in manipulating any keys.

**Comment by randy3k** [comment]
Ubuntu has a key shortcut `ctrl+alt+t` to bring up its default terminal....

**Comment by corinthian13** [comment]
Just changed the Ubuntu "Open Terminal" to Super(Cmd)+t and left CTRL+ALT+t to Terminus.
Worked straight off, pure beautiful.
Many thanks.
