### ISSUE TITLE
Alt to skip words

### ISSUE THREAD

**Issue by MeerKatDev** [randy3k/Terminus#278]
Is it possible to press alt + arrows left and right to go faster through the commands?

**Comment by randy3k** [comment]
Which shell are you using?

**Comment by MeerKatDev** [comment]
zsh

**Comment by randy3k** [comment]
Put these in your `.zshrc`.
```
bindkey -e  # emacs mode
bindkey "\e[1;3C" forward-word
bindkey "\e[1;3D" backward-word
bindkey "\e[3~" delete-char
```

I also added the last line in case you also want `delete-char`.

**Comment by randy3k** [comment]
See this section: https://github.com/randy3k/Terminus#alt-leftright-to-move-between-words-unix

**Comment by MeerKatDev** [comment]
thank you very much, really helpful!
