### ISSUE TITLE
Rulers appeared after upgrade to ST4

### ISSUE THREAD

**Issue by simov** [randy3k/Terminus#285]
![rulers](https://user-images.githubusercontent.com/1694112/119563354-19392000-bdb0-11eb-8620-a186a5f0b3f3.png)

On the top is the editor view configured with `rulers: [80]` and on the bottom is Terminus that after upgrade to ST4 inherited the rulers configuration in a way, event though it's slightly misaligned as well. Is there a way to disable this, I really don't expect to see that inside the terminal view.

**Comment by randy3k** [comment]
You just have to disable it via `view_setting` in `Terminus.sublime-settings`.

```
	"view_settings":
	{
		"rulers": []
	},
```

**Comment by randy3k** [comment]
By the way, the reason that they are misaligned is that the panel has a smaller font size. You could also fix it by changing the font size via the "view_settings".

**Comment by simov** [comment]
Thanks, that was really helpful. I was looking at the docs but I couldn't find the `view_settings` config there. I saw it mentioned in a github issue I think, so probably main readme can be updated?

**Comment by cdabel** [comment]
How about just make `"rulers": []` be the default behavior?
