### ISSUE TITLE
White lines/empty space just after each text

### ISSUE THREAD

**Issue by bitroniq** [randy3k/Terminus#29]
# Environment:
* Sublime-Text 3.1.1
* Windows 10
* Sublime Theme: Adaptive
* Sublime Color Scheme: Monokai
* Terminus Theme: Monokai
* Terminus Window: Both View and Panel
* Terminus Terminal type: any (cmd, WSL, powerline)
---
When I open terminus and i.e. list files/directory on every line just after the text there is white empty space to the end of the line. Every line.
The cursor is also white.
I've tried every theme, color scheme, terminus-theme, different shells. Always the same effect.

![terminus](https://i.imgur.com/HitIizP.png)

**Comment by randy3k** [comment]
It looks like you have installed a package which highlight trailing spaces

**Comment by bitroniq** [comment]
@randy3k thanks, it fixed the issue. Closing case.
I'm using [SublimeText / TrailingSpaces](https://github.com/SublimeText/TrailingSpaces)
I toggled to disable the highlighting and added a key to toggle on when needed:
{ "keys": ["ctrl+shift+d"], "command": "toggle_trailing_spaces" }
