### ISSUE TITLE
i am typing in terminus but i can t see the text in it

### ISSUE THREAD

**Issue by RohilPrajapati** [randy3k/Terminus#290]
screen shot of terminus text is not visible in it !!
![terminus](https://user-images.githubusercontent.com/56360150/121769728-f915a900-cb84-11eb-8161-72415de10ee7.PNG)
 
is there any solution to bring back text i have tried different thing like changing the theme of terminus but it is not working

- it dont show text in tab view as well as panel view

**Comment by randy3k** [comment]
Could you provide more details?

**Comment by RohilPrajapati** [comment]
# this sublime text 3 and in past 1 week i have been facing this problem i have remove and reinstall terminus for more then 2-4 times and its not working.. it is typing text in terminus but it is not visible line transparent text ..
terminus setting screen shot
![terminus setting](https://user-images.githubusercontent.com/56360150/121769984-565e2a00-cb86-11eb-9239-bf31d19914cc.PNG)

screen shot of pannel and tab view
![panel view terminus](https://user-images.githubusercontent.com/56360150/121769994-670ea000-cb86-11eb-8f4c-7e596d6bb486.PNG)
