### ISSUE TITLE
[Feature Request] Send code to external terminal app, such as Mac terminal or iTerm.

### ISSUE THREAD

**Issue by arshapplied** [randy3k/Terminus#291]
Do you think it is possible to run the code in an external terminal app such as Mac terminal or iTerm, using the sublime settings.

Like on build, If the app(Terminal or iTerm) is not open, it opens it , and shows the output in there.

**Comment by randy3k** [comment]
It is certainly possible but however it is out of the scope of Terminus. If you are using Windows, you could checkout this video: https://www.youtube.com/watch?v=O5conj8RqyE
A similar approach is applicable to macOS and Linux.

**Comment by arshapplied** [comment]
I tried the above version of the video for Mac, but I cannot seem to find an AppleScript , that tells Mac terminal to open the , and execute a valid shell command.

Do you think you can make something with terminal that it opens as an external window of sublime, and I can set it aside, on my desktop , and it shows the output there.

Being able to use terminus for this will be great.

**Comment by randy3k** [comment]
I am confused. Why do you need Terminus while using macOS Terminal?

**Comment by Afrowave** [comment]
Hey @arshapplied,

This is a Sublime Text issue. Here is the answer you were given on the [Sublime Text Forum](https://forum.sublimetext.com/t/send-code-output-to-mac-terminal-or-other-terminal-emulators/58867).

Would you like some help in doing it?
