### ISSUE TITLE
Font does not change

### ISSUE THREAD

**Issue by cybranker** [randy3k/Terminus#293]
Hello! When the "font_face" parameter is not set, the terminal is partially displayed well, only without icons. 
Screen 1: http://dl3.joxi.net/drive/2021/06/20/0011/1403/767355/55/0e2ab3c628.png
Screen 2: http://dl4.joxi.net/drive/2021/06/20/0011/1403/767355/55/44f430d0f5.png

Install the font that is installed on the system and contains all these icons.
Screen 1: http://dl3.joxi.net/drive/2021/06/20/0011/1403/767355/55/b0a0124bd5.png
Screen 2: http://dl3.joxi.net/drive/2021/06/20/0011/1403/767355/55/b1b9d866d4.png

The font is not applied. What could be the problem?

I have a WSL terminal and everything is fine there. 
Screen: http://dl4.joxi.net/drive/2021/06/20/0011/1403/767355/55/47cefc7dfc.png

**Comment by randy3k** [comment]
You will need a font with powerline support https://github.com/powerline/fonts

**Comment by cybranker** [comment]
> You will need a font with powerline support https://github.com/powerline/fonts

This does not work ((

**Comment by cybranker** [comment]
> You will need a font with powerline support https://github.com/powerline/fonts

Thank you so much. I've found the right font! 
Screen: http://dl4.joxi.net/drive/2021/06/21/0011/1403/767355/55/a81b2adb58.png

**Comment by randy3k** [comment]
I am glad that you figured it out.
