### ISSUE TITLE
Consider setting a conspicuous environment variable by default

### ISSUE THREAD

**Issue by frou** [randy3k/Terminus#30]
If this plugin set a conspicuous environment variable by default, such as `TERMINUS_SUBLIME=1`, we could all make use of that when adding things that are only for Terminus to our regular `bash_profile` etc files.

For example, the word-movement stuff:

```sh
# ...

if test -n "$TERMINUS_SUBLIME"; then
    bind '"\e[1;3C": forward-word'
    bind '"\e[1;3D": backward-word'
fi

# ...
```

**Comment by randy3k** [comment]
It is a great idea. It will be available in the next release.
