### ISSUE TITLE
Can't write "@" using altgr+v

### ISSUE THREAD

**Issue by cernymichal** [randy3k/Terminus#301]
_Windows 10 Pro 21H1 (build 19043)
Sublime Text 4113_

On the czech QWERTZ we write "@" using altgr+v. Sadly that is not possible in Terminus if you have the `natural_keyboard` setting set to true (I believe), since it uses ctrl+alt+v to send the literal ctrl+v.

I found a workaround by binding said combination to sending "@" as a string:
```
{
    "keys": ["ctrl+alt+v"],
    "command": "terminus_send_string",
    "args": { "string": "@" },
    "context": [{ "key": "terminus_view" }]
},
```
Even though you can't send the literal ctrl+v now, you can still copy and paste just fine.

Maybe this could be solved by adding this combination to the `preserve_keys` list.

**Comment by randy3k** [comment]
Sorry for my lack of knowledge about European keyboards. I don't have any better solutions for now than overriding `ctrl+alt+v`.
