### ISSUE TITLE
Can't use global aliases (those that are defined in .bash_aliases) in terminus window.

### ISSUE THREAD

**Issue by shambu09** [randy3k/Terminus#303]

**Comment by shambu09** [comment]
Executing source ~/.bashrc whenever I open terminus solves it.

**Comment by randy3k** [comment]
It depends on how you launch your shell. If you launch it with the login flag `-l`, it should course `.bashrc` automatically.

**Comment by shambu09** [comment]
> It depends on how you launch your shell. If you launch it with the login flag `-l`, it should course `.bashrc` automatically.

This is the settings file i use 
```
{
"default_config": {
        "linux": "Bash",    // login shell
    },
"shell_configs": [
        {
            "name": "Bash",
            "cmd": ["bash", "-l", "-i"],
            "env": {},
            "enable": true,
            "platforms": ["linux", "osx"]
        }]
}
```
Tell me if I made some mistake but the aliases don't work although there is a -l arg

**Comment by randy3k** [comment]
How did you source `.bash_aliases` in `.bashrc`?

**Comment by shambu09** [comment]
I got the solution!
The issue was I didn't source .bashrc in .bash_profile.
And bash sources .bash_aliases automatically in ubuntu 20.04.

**Comment by randy3k** [comment]
I think it is because you are running non login shell in other occasion and it sources `.bashrc` directly. 

For login shell, it sources `.bash_profile` instead and it should include 
```
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi
```
