### ISSUE TITLE
Color inconsistencies in last release + bold text missing

### ISSUE THREAD

**Issue by simov** [randy3k/Terminus#308]
Recently I restarted Sublime and it seems I got the new version of Terminus. However, I'm noticing some color inconsistencies between my default Bash terminal and Terminus:

![terminus-colors](https://user-images.githubusercontent.com/1694112/130355662-d3fa3b74-b168-4ab9-b658-c3a29355aa63.png)
> left: Bash, right: Terminus

I have been using a custom theme ever since, but I noticed that the theme config now have to use color names instead of indexes, but even with that change Terminus is picking only the background and the foreground colors and it does not react to any other color change. Also not sure where the bold style went and how to bring it back.

```json
{
  "theme": "user",
  "user_theme_colors": {
    "background": "#000000",
    "foreground": "#f8f8f2",
    // "caret": "white",
    // "block_caret": "white",
    // "selection": "#444444",
    // "selection_foreground": "#ffffff"

    "black": "#555753",
    "red": "#EF2929",
    "green": "#8AE234",
    // "brown": "#cdcd00",
    "blue": "#729FCF",
    "magenta": "#AD7FA8",
    "cyan": "#34E2E2",
    // "white": "#e5e5e5",

    // "light_black": "#7f7f7f",
    // "light_red": "#ff0000",
    // "light_green": "#00ff00",
    // "light_brown": "#ffff00",
    // "light_blue": "#5c5cff",
    // "light_magenta": "#ff00ff",
    // "light_cyan": "#00ffff",
    // "light_white": "#ffffff"
  },
  "view_settings": {
    "rulers": [],
    "font_face": "Monospace",
    "font_size": 10.5,
  },
}
```

I'm using Ubuntu 18.04 and ST4

**Comment by simov** [comment]
This is how `adaptive` looks like on my end:

> This one seems completely off

![terminus-adaptive](https://user-images.githubusercontent.com/1694112/130365551-549a1ddc-0ded-4a83-ad3d-323949ad6853.png)

This is the `classic` one:

> This one picks the cyan and the green correctly, but the blue is dark blue

![terminus-classic](https://user-images.githubusercontent.com/1694112/130365574-7cfe81eb-ae43-44bc-b4fe-3ebc65a178d0.png)

This one is using my custom `user` theme:

> This one only picks the background from my custom theme, none of the ANSI codes work

![terminus-user](https://user-images.githubusercontent.com/1694112/130365625-deb3f84e-3386-4b2a-83ff-b7d4ed449376.png)

And this is how my terminal look like:

> The bold text was not detected at all in terminus

![terminal](https://user-images.githubusercontent.com/1694112/130365666-03942c31-cb9e-4f2c-812e-81edf41e9101.png)

Before latest update my terminal and terminus looked identical using this theme:

```json
{
  "theme": "user",
  "user_theme_colors": {
    "background": "#000000",
    "foreground": "#f8f8f2",
    // "caret": "white",
    // "block_caret": "white",
    // "selection": "#444444",
    // "selection_foreground": "#ffffff"

    "00": "#555753", // black
    "01": "#EF2929", // red
    "02": "#8AE234", // green
    // "03": "#cdcd00", // brown
    "04": "#729FCF", // blue
    "05": "#AD7FA8", // magenta
    "06": "#34E2E2", // cyan
    // "07": "#e5e5e5", // white

    // "08": "#7f7f7f", // light_black
    // "09": "#ff0000", // light_red
    // "10": "#00ff00", // light_green
    // "11": "#ffff00", // light_brown
    // "12": "#5c5cff", // light_blue
    // "13": "#ff00ff", // light_magenta
    // "14": "#00ffff", // light_cyan
    // "15": "#ffffff" // light_white
  },
  "view_settings": {
    "rulers": [],
    "font_face": "Monospace",
    "font_size": 10.5,
  }
}
```

**Comment by randy3k** [comment]
Looks like you didn't define the light color. The recent version of Terminus has a new setting to brighten bike text.

**Comment by randy3k** [comment]
I would suggest you to dup all the normal colors to light colors if you don’t need the feature.

**Comment by simov** [comment]
Ok, that fixed the color issues:
![terminus-light](https://user-images.githubusercontent.com/1694112/130367236-62cf75c4-2841-4895-8464-4c8c9f19b921.png)


Compared to:
![terminal-light](https://user-images.githubusercontent.com/1694112/130367217-d6fb838e-de65-443a-a742-67b273a56df2.png)

But the bold style is nowhere to be seen. Is there anything else I can do to bring it back?

**Comment by randy3k** [comment]
The bold style is not supported, nor it was never supported. The new setting is a workaround for the bold text.

**Comment by simov** [comment]
I'm using Terminus since around March 2020 and up until `v0.3.18` my Bash terminal and Terminus looked identical and bold text was definitely rendered correctly.

I'm using GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu) on Ubuntu 18.04 on ST3 at that time and now using ST4.

Again with the above setup, and up until `v0.3.18`, bold text was rendered correctly and the color was also brightened up correctly as well, because I was not specifying the lighter colors explicitly in my `user` theme.

As far as I understand the new `brighten_bold_text` option in `v0.3.19` was introduced to simulate what I have in Bash here (the checkbox at the bottom):

![Screenshot from 2021-08-23 09-56-54](https://user-images.githubusercontent.com/1694112/130403919-d5636ed8-9850-4bed-a34c-9f9d1ecc39f1.png)

but that option has no effect whatsoever with my setup above. It simply doesn't work on any theme preset: `classic`, `adaptive` or the `user` one, and again that's besides that fact that the bold text is no longer rendered as bold text as it was in `v0.3.18`.

**Comment by randy3k** [comment]
> bold text was definitely rendered correctly.

It is impossible. Bold text was never supported in Terminus.

> bold text was rendered correctly and the color was also brightened up correctly as well, because I was not specifying the lighter colors explicitly in my user theme.

Without the lighter colors in the settings, it is using the colors from the "classic" theme. I'll be surprised to learn that the colors are the same as those of your terminal.

**Comment by simov** [comment]
Ok, that might be my mistake about the bold test. It's probably my mind playing tricks on me, which is funny because I'm looking at that same terminal every single day. In any case, colors look identical with my terminal now so that works for me :+1:
