### ISSUE TITLE
Windows 'teminus_exec' seems to not work for cargo builds: "couldn't determine self executable name"

### ISSUE THREAD

**Issue by photex** [randy3k/Terminus#310]
Howdy!

I have a simple build system:

```json
"target": "terminus_exec",
            "cancel": "terminus_cancel_build",
            "cmd": [
                "cargo", "check"
            ],
            "working_dir": "$project_path",
```

On MacOS and Linux this works perfectly fine. One windows I get the following error:

```
error: couldn't determine self executable name                                                                                                                         
[Finished in 0.41s with exit code 1]
```

Seems isolated to cargo, and even rustup. They are on in PATH, and from a terminus shell I can run this command successfully.

The regular "exec" has no trouble running cargo. And I can also use the built-in RustEnhanced targets. So I'm not stuck, but I'm bothered trying to understand why this would be happening specifically in a terminus build context.

Any ideas?

**Comment by eugenesvk** [comment]
@photex I see that you've closed the issue as completed, but I have the same issue. How did you resolve it? Thanks!

**Comment by photex** [comment]
After months of no response I uninstalled the extension and carried on with life. Switching to Vscode even though sublime is still my preference is just how it’s going in 2022 I guess.

**Comment by eugenesvk** [comment]
FYI in the linked issue I've found the root cause - outdated winpty; can be manually patched to make it work with cargo
