### ISSUE TITLE
failed to activate (on_activated_async)

### ISSUE THREAD

**Issue by alvarolm** [randy3k/Terminus#317]
today I noticed that after switching between projects active terminals are no longer active, I enabled the debug in settings and as soon as I switch the console spits out:

DEBUG:Terminus:close
DEBUG:Terminus:renderer breaks
DEBUG:Terminus:cleanup

I'm using:
terminus v0.3.21
sublime 4113

active, working terminal:
![active](https://user-images.githubusercontent.com/2561547/132136207-5da9be51-377a-403e-aa4b-48a1eb6dd88d.png)

inactive, not working terminal, after switching between projects:
![inactive](https://user-images.githubusercontent.com/2561547/132136209-47472d2a-492a-45ae-8aed-6711d9ef5dac.png)

any clues are appreciated, thanks in advance

UPDATE:

~~just downgraded to terminus v0.3.19 and terminals restart correctly, they activate after switching projects, since:~~
~~https://github.com/randy3k/Terminus/commit/89da62bef6069f28fd6b7e481be1ffb74cf95574~~
~~seems to be the only change, the issue might lay in there~~

pin pointed the issue to commit  https://github.com/randy3k/Terminus/commit/edc4e3071c959462ac23a13d2741883ba16fe988

"is_widget" setting value documentation seems to be a little flaky (sublime hq fault).
why to exclude non widgets views form activation (in my case seems not to be a widget but report as it is) ?
in my opinion it should be excluded from activation only non visible views.

**Comment by scm-unimelb** [comment]
also experiencing Terminus is 'unresponsive' when I quick switch out of project and back, or when I launch Sublime. I create a new tab with a fresh Terminus instance and that works fine until I quit Sublime again. I only noticed this in the last few days - 
the same symptoms on two different machines with 
Terminus 0.3.20
Sublime build 4113 
on Linux Mint 20.2

after switch project and return the console says:
DEBUG:Terminus:mode: [7, 25], cursor: 36.2
DEBUG:Terminus:reset cursor
DEBUG:Terminus:close
git: untracking working dir /home/.....
DEBUG:Terminus:renderer breaks
DEBUG:Terminus:cleanup
git: tracking working dir /home/.....

Terminus then does not respond to keystrokes, but I can click to move cursor and select text in the path prompt

**Comment by randy3k** [comment]
Sorry about it. It should be fixed now.
