### ISSUE TITLE
New Text During Command in Terminal Tab Pulls Scroll Bar to Bottom 

### ISSUE THREAD

**Issue by divingskyward** [randy3k/Terminus#33]
This behavior is different than I experience in Ubuntu 16.04 in terminal. Typically when I scroll up, the command keeps outputting text and doesn't pull me to the bottom as text is output. It's very helpful to be able to inspect text while the command continues to run and not be forced to the latest output. To reproduce, scroll up while running a long command that continuously outputs and let off the mouse buttons and/or scroll wheel.

**Comment by randy3k** [comment]
Thank for opening the issue. I have noticed this issue but was lacking the momentum to fix it. So here is the fix.

**Comment by divingskyward** [comment]
Awesome - thanks for the fast responses!!!
