### ISSUE TITLE
Terminus Window with Powershell does not show icon

### ISSUE THREAD

**Issue by doantranthanh** [randy3k/Terminus#335]
Hi all,

I am having a problem with NERD font in my view window

As you can see, the icon is not showing

![image](https://user-images.githubusercontent.com/9557564/150488320-4efda610-57a4-4fad-bcbe-a7fd0dd37b61.png)

But in powershell it is showing well

![image](https://user-images.githubusercontent.com/9557564/150488448-fbd79fb9-836b-4f31-9bd0-fa7f310da065.png)

I tried to change the font_face to

![image](https://user-images.githubusercontent.com/9557564/150488527-fed7f00e-be5e-4f56-892d-6174476d6024.png)

But it does not work. I am new to Sublime so please could you help me?

Many thanks

**Comment by doantranthanh** [comment]
I install this font 

https://github.com/romkatv/dotfiles-public/blob/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf

And change to 

`"view_settings":{
		"font_face": "MesloLGS NF",
		"font_size": 12
	},`
	
	Then it is working now

**Comment by tianshaohan** [comment]
Thanks  a lot. @doantranthanh

**Comment by brucmao** [comment]
There are still some unsupported
powershell
![image](https://user-images.githubusercontent.com/6119652/179895839-5bcb6d30-7db0-4190-bcba-8c42ebfc6a8f.png)
sublime text
![image](https://user-images.githubusercontent.com/6119652/179895911-bb19df7b-be74-45a8-863d-089412b094d3.png)
