### ISSUE TITLE
Terminus closes immediately after execution from a plugin

### ISSUE THREAD

**Issue by abiz** [randy3k/Terminus#34]
I tried to run terminus from a plugin but it immediately closes, is there a way to keep it open? I have provided a small example of what I'am trying to do.

    import sublime
    import sublime_plugin

    class HelloWorldCommand(sublime_plugin.TextCommand):
        def on_select(self, item):
            window = self.view.window()
            item = self.items[item]
            window.run_command(
                "terminus_open", {
                    "config_name": "Default",
                    "cmd": ["echo", item]
                }
            )
            print(item)

        def run(self, edit):
            window = self.view.window()
            self.items = ["hello", "world"]
            window.show_quick_panel(self.items, self.on_select);

Thanks for a great plugin btw!

**Comment by randy3k** [comment]
currently, the window will be closed automatically if the process ends successfully. so i guess we need an option to make it persistent

**Comment by randy3k** [comment]
There is a new option called `auto_close` in ef81a73. A new release will be published soon. Thanks.
