### ISSUE TITLE
Disable shortcuts for tabs navigation

### ISSUE THREAD

**Issue by lapega** [randy3k/Terminus#36]
Ubuntu 18.04 here.
I use Ctrl+(PageUp|PageDown) to navigate between tabs, but when in terminus tab that shortcut doesn't work (it writes some characters).
Need some kind of command, like 'do-nothing' to put in the terminus shortcuts file and overwrite the default action.

**Comment by randy3k** [comment]
Terminus sends ctrl+pagedown and pageup to the terminal process. For now, you could override those command manually. In a long run, i would like to set a mechanic to disable any  of the keys.

**Comment by lapega** [comment]
> you could override those command manually
But I don't know what command is associated to change tab action, so I can't put anything in the user shorcuts file.

**Comment by randy3k** [comment]
You just need to put
```
	{ "keys": ["ctrl+pagedown"], "command": "next_view" },
	{ "keys": ["ctrl+pageup"], "command": "prev_view" },
```
in your user keymap file.

**Comment by lapega** [comment]
Yes! that works!
Thx
