### ISSUE TITLE
Unable to use special characters within Terminus

### ISSUE THREAD

**Issue by merc1er** [randy3k/Terminus#366]
Special characters requiring specific key combinations are not input into Terminus on macOS. For example, the `{` character has the following key combination (macOS - AZERTY keyboard): `option` + `(`. Same goes for `}`, `|` and so on.

This restricts considerably the convenience of Terminus as these characters are common for developers.

**Comment by randy3k** [comment]
You might need to override some of the keybindings in https://github.com/randy3k/Terminus/blob/master/Default.sublime-keymap
Try the following, though I haven't tested it as I don't own any keyboards other than standard US QWERTY.
```
{ "keys": ["alt+f5"], "command": "terminus_keypress", "args": {"key": "{"}, "context": [{"key": "terminus_view"}] },
```

**Comment by merc1er** [comment]
I tried this but it doesn't seem to be overwriting keys.  
Just to be sure, I add this line to `Preferences > Package settings > Terminus > Command palette` right?

I tried adding:
```
{ "keys": ["a"], "command": "terminus_keypress", "args": {"key": "{"}, "context": [{"key": "terminus_view"}] },
```
But pressing `a` still shows `a`.

**Comment by choallin** [comment]
@merc1er Did you find a solution? I'm using a germain keyboard on a mac and have the same problems...

**Comment by merc1er** [comment]
> @merc1er Did you find a solution? I'm using a germain keyboard on a mac and have the same problems...

No, sadly I could not get it to work even after re-binding keys 😢

**Comment by randy3k** [comment]
@merc1er

Actually, the setting should go to Preferences: Terminus Keybindings

![image](https://user-images.githubusercontent.com/1690993/230141802-6d6a009b-8957-4663-a62e-54ac46c4a897.png)

**Comment by merc1er** [comment]
> @merc1er
> 
> Actually, the setting should go to Preferences: Terminus Keybindings
> 
> ![image](https://user-images.githubusercontent.com/1690993/230141802-6d6a009b-8957-4663-a62e-54ac46c4a897.png)

Oh, yes. That worked!

@choallin here is what I added for it to work on a French Apple keyboard:

```json
{ "keys": ["alt+5"], "command": "terminus_keypress", "args": {"key": "{"}, "context": [{"key": "terminus_view"}] },
{ "keys": ["alt+)"], "command": "terminus_keypress", "args": {"key": "}"}, "context": [{"key": "terminus_view"}] },
```

**Comment by titouanmathis** [comment]
For people having the same issue for French keyboards, I published a complete mapping [here](https://github.com/titouanmathis/sublime-text-terminus-keymap/blob/main/terminus-macos-fr.sublime-keymap) which can be copy-pasted.
