### ISSUE TITLE
Toggle panel command should hide the panel when run via the Command Palette

### ISSUE THREAD

**Issue by eugenesvk** [randy3k/Terminus#369]
`Toggle panel` command seems to have different behavior depending on how you run it:
- it toggles (shows/hides) the panel when run via a keybind
- it only shows (but doesn't hide) the panel when  run via the **Command Palette**

I'm guessing it checks for an active panel and the Command Palette panel is topmost, so instead of hiding the panel, it focuses it instead

It might be beter to make the behavior consistent and if you invoke the command while within the Terminus panel from the Command Palette, it should hide the Terminus panel just like if you pressed a shortcut

**Comment by randy3k** [comment]
Happy new year.

It is unfortunately a behavior control by sublime text itself. Its `show_panel` command decided not to hide the terminal when triggered from the command palette. 

It is now fixed with 8096d8fc9fef7a771824243b533f1ed96b498c06. Will make a release soon.
