### ISSUE TITLE
Sublime ask to save terminus tab

### ISSUE THREAD

**Issue by lapega** [randy3k/Terminus#37]
When closing the terminus tab, Sublime Test asks to save the file.
Can you put an option to allow us to close it without warning?

Thank you!

**Comment by randy3k** [comment]
that’s strange. Are you sure it is not due to one of you installed packages? Terminus should handle file closing well.

**Comment by lapega** [comment]
Mmm, I don't know. I have installed a lot of packages, but no one about terminal or saving documents. 
I could uninstall all packages except terminus, but since is a production PC, can't do that .

**Comment by randy3k** [comment]
Try running `sublime.log_commands(True)` in the console (<kbd>ctrl + `</kbd>) and see what command is being triggered when you close the terminal.

**Comment by lapega** [comment]
Nothing happens.
I'm attaching a screenshot:
![captura de pantalla de 2018-08-15 19-54-55](https://user-images.githubusercontent.com/572502/44177655-4156a900-a0c5-11e8-955a-2f51268347c4.png)

**Comment by randy3k** [comment]
How did you close the window? Ctrl+w? or Click the close button?

**Comment by lapega** [comment]
Both methods, same result.
I can see that sometimes the console log puts:

> process is terminated with return code None.

**Comment by randy3k** [comment]
While opening a Terminal, could you go to the sublime console (<kbd>ctrl+`</kbd>) and report the result of `view.is_scratch()`.

**Comment by lapega** [comment]
Here:

>  >>> ofview.is_scratch()
> Traceback (most recent call last):
>  File "<string>", line 1, in <module>
> NameError: name 'ofview' is not defined

**Comment by lapega** [comment]
Yep!
> view.is_scratch()
> False

**Comment by randy3k** [comment]
The view is supposed to be set as scratch by Terminus. there is a high chance that a package that you installed is marking it not a scratch.

**Comment by lapega** [comment]
Ok, this are the installed packages:

- ColorPicker
- Emmet Css Snippets
- HTML
- jsonschema
- PHP
- PHP_CodeSniffer
- php-completions
- php-grammar
- php-snippets
- ptyprocess
- pyte
- python-jinja2
- PyV8
- Rails
- SublimeCodeIntel
- Terminus
- wcwidth
- zzz A File Icon zzz

**Comment by lapega** [comment]
Same problem with [TerminalView](https://github.com/Wramberg/TerminalView),
I'll keep that package because typing seems more fluid.

Thanks a lot!

**Comment by randy3k** [comment]
No problem. But I also still curious what was causing your particular issue. If you figure it out, please let me know.

**Comment by lapega** [comment]
Of course!
When doing searches, the search result is showed as a scrach and don't ask to save. 
So the behavior only occurs with both terminal packages.

I have set Tilix as replacement of gnome-terminal, perhaps the problem is there?
