### ISSUE TITLE
Crash when Mac tries to load a Ubuntu terminal tab

### ISSUE THREAD

**Issue by Endermanbugzjfc** [randy3k/Terminus#371]
I dual-boot Mac and Ubuntu and have my programming workspaces in a shared FAT32 partition. I have Terminus in both my Sublime Text installations.

However, whenever I use my Mac Sublime Text installation to load a project containing any Ubuntu terminal tab, the whole Sublime Text freezes and stops responding until I force-quit it. I must either disable Terminus before opening it or delete the project.sublime-workspace file to reset project tabs.

# Environment
- **Mac**: 12.4
- **Ubuntu**: 22.04
- **Sublime Text**: Build 4126
- **Terminus**: 0.3.27
- **Shell**: Bash

**Comment by randy3k** [comment]
Normally, it shouldn't freeze sublime text. But anyway, I added a setting `reactivate_terminals` to not reactivate terminals when the window is re-opened.
