### ISSUE TITLE
Windows: termius.exe gets deleted and termius only runs through the termius-updater

### ISSUE THREAD

**Issue by Issykul** [randy3k/Terminus#379]
I don't really know how I can provide good info on this. But after ssh'ing into my server via termius and closing the application afterwards, it looks like termius got uninstalled.

I am still able to find the "updater" in the following path: `C:\Users\<username>\AppData\Local\termius-updater\installer.exe`
and am able to start termius this way. It looks like termius gets reinstalled for the while it is running. But after i close it all my shortcuts break again.

**Comment by Issykul** [comment]
Sorry for opening an unnecessary issue here on GitHub. Downloading the installer.exe from https://www.termius.com/windows and running it resolved the issue.

Weird nonetheless.

**Comment by randy3k** [comment]
Please note that it is the repo of Terminus, a plugin for Sublime Text, not Termius.

**Comment by Amphyby** [comment]
Faced same issue after yesterday's update. Termius was ready for update. Was closed automatically with win shutdown. On boot there was no such executable.
Glad that after installation from MicrosoftStore all the settings were picked up. Still weird disappearance.
