### ISSUE TITLE
termius shows blank 

### ISSUE THREAD

**Issue by ruhollahah** [randy3k/Terminus#387]
After I ran termius it shows nothing, I reinstalled termius and nothing happened.
![Screen Shot 2023-02-26 at 10 36 25](https://user-images.githubusercontent.com/116563609/221397146-9d98294e-feb8-4fc8-95e7-5821dac602e9.png)

**Comment by CN-xukaixuan** [comment]
> After I ran termius it shows nothing, I reinstalled termius and nothing happened. ![Screen Shot 2023-02-26 at 10 36 25](https://user-images.githubusercontent.com/116563609/221397146-9d98294e-feb8-4fc8-95e7-5821dac602e9.png)

I have the same problem. Is there any solution?

**Comment by g-salib** [comment]
me to the same issue also tried to remove and install again and nothing happened

**Comment by CN-xukaixuan** [comment]
It is assumed that the termius application was automatically updated, resulting in an unknown conflict error with the computer. I tried to install an old version of termius, which can be used normally now

**Comment by kraftcode-source** [comment]
@CN-xukaixuan which version did you install

**Comment by CN-xukaixuan** [comment]
> @CN-xukaixuan which version did you install

Version 7.28
But I read somewhere that the latest version seems to have fixed this blank problem, I don't know if the message is true, I didn't test

**Comment by neto-developer** [comment]
Same here, but no update available.

![image](https://github.com/randy3k/Terminus/assets/844693/7e5026da-4c70-45eb-be14-f8955849c691)
![image](https://github.com/randy3k/Terminus/assets/844693/637ed123-a6fb-46bb-b24c-f06b87478f0d)

**Comment by neto-developer** [comment]
Updated here to v8.0.0 seems to have resolved the issue.

**Comment by randy3k** [comment]
it is the repo for Terminus, a package of Sublime Text, not related to termius at all.
