### ISSUE TITLE
Toggle Terminus panel closes it

### ISSUE THREAD

**Issue by UkoeHB** [randy3k/Terminus#391]
I have a simple key binding that has worked for years:

```
{
    "keys": ["ctrl+x"],
    "command": "toggle_terminus_panel",
    "args"   : {
        "cwd": "${file_path:${folder}}"
    }
},
```

In the past when the panel was active but not in focus and I used the key binding, then the panel would become in focus (very convenient). Now when I use the key binding the panel closes itself. How can I recover the old behavior?

**Comment by kaste** [comment]
That is a regression from https://github.com/randy3k/Terminus/commit/8096d8fc9fef7a771824243b533f1ed96b498c06 I think. 😞
