### ISSUE TITLE
Unique .sublime-syntax for terminal views

### ISSUE THREAD

**Issue by JJMorton** [randy3k/Terminus#413]
It would be useful to have terminus views open with a custom syntax (named e.g. "Terminus"), rather than just "Plain Text".
This would allow the user to create a syntax-specific preferences file to disable packages, for example.
The syntax would simply act as plain text does, so wouldn't change any behaviour.

Considering how easy this would be to implement, I suspect there might be a reason why it hasn't been done, but I couldn't find anything relevant in previous issues.

Thanks

**Comment by randy3k** [comment]
It is a great idea. Implemented in fe0507f.

**Comment by JJMorton** [comment]
Thanks, it works great!
Just a note, with the syntax named "Terminus.sublime-syntax", the corresponding syntax specific settings are saved in "Terminus.sublime-settings", the same file used for the terminus preferences. Maybe this is not a problem, but the syntax might be better named something else to avoid clashes.

**Comment by randy3k** [comment]
Do you have any suggestion? Terminus View?

**Comment by JJMorton** [comment]
"Terminus View" or "Terminus Terminal" would do the job I think.

**Comment by randy3k** [comment]
renamed the file to "Terminus View" 88e46b9.

**Comment by JJMorton** [comment]
Looks good!
