### ISSUE TITLE
Terminus in view does not type left bracket

### ISSUE THREAD

**Issue by albertostefanelli** [randy3k/Terminus#42]
This happens with Sublime Text 3 (Build 3176) with x86_64-apple-darwin15.6.0 (64-bit) running under macOS High Sierra 10.13.6. Copying and pasting `(` works.

**Comment by randy3k** [comment]
I believe it is because you have overrides the `(` key in your user keyking settings or by other packages. Use `sublime.log_commands(True)` to verify it.

**Comment by randy3k** [comment]
Terminus is just a tty device, it just sends what you type to the process. By the way, why did you redefine this keybind in your user file!? the default settings come with this already.

**Comment by albertostefanelli** [comment]
Just to be clear, any macro or keybinding do not work in terminus?

Also, thanks for the clarification on the settings, i usually paste and copy everything in the user-defined settings but that might be not necessary.

**Comment by randy3k** [comment]
Not sure what you meant when you said “any keybinding”. Obviously, copying and pasting are working....

Just think that it is s regular terminal, nothing fancier than it.

By the way, it is very much discouraged to copy all the default keybindings to your user settings. Only override the ones you need to override (if it is necessarily needed)

**Comment by albertostefanelli** [comment]
Thanks so much for the clarification! I close
