### ISSUE TITLE
Terminus stopped working 

### ISSUE THREAD

**Issue by blackjyn** [randy3k/Terminus#424]
I don't know what happened . Terminus stop working .

I already installed, reinstall, everything, clean the registry, clearing the cache et cetera but it is just stopped working .
I cannot open Terminus, toggle it, I can't even list shell.

System:

Sublime text 4 build 4169 on Windows 11

**Comment by piimah** [comment]
same here. 

em on win10 and sublime updated to the latest version few days ago. since then terminus stopped working. 

i tried different sublime versions and 4169 seems to work without any problems.

don´t know what the problem was but em fine with 4169 for now:)

**Comment by blackjyn** [comment]
unfortunately I have to do clean install of the latest ST4 so that it worked again
Never facing this kind of issue before.
