### ISSUE TITLE
How to open panel in current file directory.

### ISSUE THREAD

**Issue by h2110100** [randy3k/Terminus#428]
I know that opening the terminus tab in current file directory can be done through
```
"command": "terminus_open",
		"args": {
			"cwd": "${file_path:${folder}}"
		}
```
but is there a way to do so with 
```
"command": "toggle_terminus_panel" ?
```
because i tried 
```
"command": "toggle_terminus_panel",
		"args": {
			"cwd": "${file_path:${folder}}"
		}
```
and it doesnt work.

**Comment by randy3k** [comment]
`toggle_terminus_panel` may reuse panel, therefore it doesn't always respect the given argument.
If you want to open a terminal in panel, you just need to specify `panel_name` in `terminus_open`.
