### ISSUE TITLE
terminus_exec always closes the output panel

### ISSUE THREAD

**Issue by OdatNurd** [randy3k/Terminus#429]
As indirectly reported in the Sublime Discord by `flintspike`, `terminus_exec` always closes and deletes the panel as soon as the build finishes, regardless of success or failure of the command.

The reason seems to be because of a change made in response to #410 , which modified the code in `terminus_exec` in regards to the `auto_close` setting;

Previously:

```python
        if "auto_close" not in kwargs:
            kwargs["auto_close"] = False
```

it is now:

```python
        if "auto_close" not in kwargs:
            kwargs["auto_close"] = "always"
```

hence, any build using `terminus_exec` needs to explicitly set `auto_close` to a different value in order to be able to potentially see the output of the build. 

Although this is indeed possible, it breaks with the convention of `terminus_exec` being a drop-in replacement for `exec` in builds.

**Comment by randy3k** [comment]
Thank you for bringing it up. It is my shortslightedness. Reverting the default setting to False.
