### ISSUE TITLE
[Feature] Does it possible to split terminal window vertically or horizontally by keybindings?

### ISSUE THREAD

**Issue by awakenine** [randy3k/Terminus#46]
I very like Terminus. Could you help me to create keybindings for windows splitting after it's opened?

**Comment by randy3k** [comment]
Check the Origami command over README

**Comment by awakenine** [comment]
@randy3k, thank you! Maybe you know how to add auto-destroy Origami pane after exit the terminal?

**Comment by randy3k** [comment]
It is not possible for the moment.
