### ISSUE TITLE
adaptive theme

### ISSUE THREAD

**Issue by randy3k** [randy3k/Terminus#5]
it would be nice to have an adaptive console theme which depends on the user color scheme. Check https://github.com/Wramberg/TerminalView/pull/53 for an attempt in TerminalView.

**Comment by KevinSjoberg** [comment]
This would indeed be a very nice addition. 🙂

**Comment by dreamcat4** [comment]
Until then,
Here are some better default colors which work well with the Material theme. And perhaps other themes. If you put this in your terminus settings. Then you may need to change only the `background` color to match your current theme.

These colors are suitable for a 'dark' type of a theme.

```json
    "theme": "user",

    // change `theme` to "user" if you want to use customized theme
    // see https://www.sublimetext.com/docs/3/color_schemes.html#colors for the
    // available colors
    "user_theme_colors": 
    {
      "background": "#253238",
      "foreground": "#829395",
      // "caret": "white",
      // "block_caret": "white",
      // "selection": "#444444",
      // "selection_foreground": "#ffffff",
      "00": "#063541",  // black
      "01": "#DB312E",  // red
      "02": "#849900",  // green
      "03": "#B48800",  // brown
      "04": "#258AD1",  // blue
      "05": "#D23581",  // magenta
      "06": "#29A097",  // cyan
      "07": "#EDE7D4",  // white
      "08": "#002A35",  // light_black
      "09": "#CA4A15",  // light_red
      "10": "#576D74",  // light_green
      "11": "#647A82",  // light_brown
      "12": "#829395",  // light_blue
      "13": "#6B70C3",  // light_magenta
      "14": "#92A0A0",  // light_cyan
      "15": "#FCF5E2"   // light_white
    },

    "view_settings": {
      // these are extra view settings which are passed to the terminus_view,
      // you could change settings like "font_face", "font_size" and paddings.
      "font_size": 12,
    },
```

**Comment by mitranim** [comment]
Now that ST~~4~~ has `"theme": "auto"` and `"color_scheme": "auto"`, Terminus feels out of place with its own fixed theme. Using the ST theme / color scheme would be very nice!

**Comment by mitranim** [comment]
On second thought, I'm surprised by the apparent lack of an option to use _no_ theme at all. Simply letting ST use the global theme and color scheme would be as adaptive as it gets. Setting `"theme"` to `"empty"` in Terminus preferences doesn't do it, as it still tries to look for a file with an empty basename. I don't know if this is hard to support, but should be significantly simpler than developing an additional theme.

**Comment by randy3k** [comment]
As explained in #263, we will need to customize the theme in order to support colors. An arbitrary theme won't work.

**Comment by randy3k** [comment]
Thanks @jwortmann. The adaptive theme is available in the current master branch.
