### ISSUE TITLE
Last directory removed, Terminus no longer works

### ISSUE THREAD

**Issue by bphunter1972** [randy3k/Terminus#51]
Presumably, the last working directory my shell was in is cached someplace within Terminus. Unfortunately, that directory now no longer exists. Now, launching Terminus leads to this error in the console:

```
  File "/Users/bphunter/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/commands.py", line 239, in <lambda>
    lambda x: on_selection_method(x, config_name)
  File "/Users/bphunter/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/commands.py", line 245, in on_selection_method
    self.run(config_name)
  File "/Users/bphunter/Library/Application Support/Sublime Text 3/Packages/Terminus/terminus/commands.py", line 163, in run
    raise Exception("{} does not exist".format(cwd))
Exception: /Users/bphunter/<mydir> does not exist

```

**Comment by randy3k** [comment]
I won’t call it a bug. You need to be sure that the working directory exists

**Comment by bphunter1972** [comment]
Is there a way to clear that cache? Because the directory is gone.

Or, jump back to the home directory if it doesn’t exist?

**Comment by randy3k** [comment]
You just need to open another window

**Comment by bphunter1972** [comment]
There are no windows open. I run any of the following and it fails with the above:
* Open Default Shell in View
* Open Default Shell in Panel
* List Shells --> Select any one, they all don't work.

I've closed all windows, quit out of ST3, and changed projects. Finally, I removed the terminus package, then re-installed it. 

And it still fails. Surely I'm not the only one seeing this?

**Comment by randy3k** [comment]
That’s odd. I cannot reproduce it.

**Comment by randy3k** [comment]
Terminus doesn't create any directory. In default settings, it uses the first folder of the current window as the working directory of the shell. Could you make sure that the erroneous folder has been removed from sidebar?

**Comment by bphunter1972** [comment]
Reinstalled and it worked!

Probably the only issue then is better error reporting and exception handling.

Great package, btw!

**Comment by randy3k** [comment]
I guess the message `<directory> does not exist` is already quite clear for what it means.

**Comment by bphunter1972** [comment]
True. But I had to open the panel to see it.

NM. It’s a fine package.

**Comment by symera** [comment]
I had a similiar problem.
To reproduce the issue, you can do the following:

Go to "Project" -> "Edit Project" and replace the text with the following code:
`{
	"folders":
	[
		{
			"path": "/some/nonexistent/path"
		}
	]
}`

Then save, close Sublime and restart.
Terminus can then no longer be started.

**Comment by randy3k** [comment]
It is an expected error if the directory to open does not exist

**Comment by symera** [comment]
Well, it's hard for a user to understand why Terminus doesn't open if _only_ the directory doesn't exist in the project settings.

If you are aware of this, just change the corresponding line and it is done, but if you don't know about the non-existent path in the project settings, you are forced to create a new project to open Terminus.

**Comment by randy3k** [comment]
But it is a common problem for all Sublime packages. I don’t see how it only affects Terminus only. Users are responsible for such operation errors. And alternative solution is to specific the `cwd ` argument. Check README for details

**Comment by symera** [comment]
Yes I agree, it doesn't affect Terminus only.
But if Sublime doesn't consider it a problem that there are still old paths in the project settings, couldn't we catch the exception and show a dialog in order to point out the non-existent path to the user?

**Comment by bphunter1972** [comment]
+1

**Comment by randy3k** [comment]
A solution is to open `$HOME` is the directory does not exist.

**Comment by symera** [comment]
Thank you.
