### ISSUE TITLE
terminus becomes very slow after running thousands of line of code 

### ISSUE THREAD

**Issue by albertostefanelli** [randy3k/Terminus#53]
after running approximately 10k lines of code the terminal gets progressively slower. 
Tested with R and rtichoke both last versions on mac os. 
Closing the terminal and relaunching it solves the problem

**Comment by randy3k** [comment]
It does slow down a bit after 10000 lines on my computer. Though it is not very noticeable. 

related to https://github.com/randy3k/Terminus/issues/25

We may add an option to control the number of lines in history.

**Comment by albertostefanelli** [comment]
That would be great! Thanks

**Comment by randy3k** [comment]
Checkout v0.2.13.

**Comment by jknguyen621** [comment]
I just did a laptop refresh at my work going from WIndows 10 to MacBook Pro M4, switching from Mputty multi-terminal to actually paying for Termius $120/year, and the performance is horrendous.  Can you please give the option on not not using SFTP for file copy? I am already in behind a firewall, with VPN and SCP itself via SSh is 10000x faster than this SFTP crap.  Please fix it ASAP, this feature of SFTP will crash your product line. GIve an alternative choice at least. Why am I paying $120 a year extra to slow me down by hours in a day, as I have to trransfer GB file size all the time.  Please make this a high priority, abiility to disable SFTP, just use SCP via SSH!!!!
