### ISSUE TITLE
I don't use ctrl+p (Goto Anything...)

### ISSUE THREAD

**Issue by ErickTucto** [randy3k/Terminus#54]
If I use `ctrl+p` must show *Goto Anything...*
It seems that the shortcut was replaced by the shortcut of the terminal.
There is a way that the sublime keyboard shortcut dominates the terminal

---
![seleccion_022](https://user-images.githubusercontent.com/22831024/46172050-0b7e1600-c268-11e8-980a-d879c0b7e160.png)

**Comment by randy3k** [comment]
It’s because there is only one view called “Terminus” in your window.

**Comment by ErickTucto** [comment]
No, if there are several views. Only that I took Terminus aside to take the capture

**Comment by randy3k** [comment]
I can't reproduce
<img width="675" alt="screen shot 2018-09-27 at 4 42 11 pm" src="https://user-images.githubusercontent.com/1690993/46173493-661d6f00-c274-11e8-857e-37051e0274d4.png">

**Comment by schmiidt** [comment]
I have added the following keybinding to enable Goto Anything while Terminus has focus.

```
[
  { "keys": ["ctrl+p"], "command": "show_overlay", "args": {"overlay": "goto", "show_files": true}, "context": [{"key": "terminus_view"}] },
]

```

**Comment by randy3k** [comment]
Oh. I got your point. `ctrl+p` is sent to the terminal instead of Sublime Text directly.

@schmiidt is right, you'll need to override the keybind for `ctrl+p` as well as many other commands.

**Comment by ErickTucto** [comment]
@schmiidt thank you very much. Perhaps, Terminus will have a list of keyboard shortcuts that you do not want to eliminate

Example
---
![seleccion_021](https://user-images.githubusercontent.com/22831024/46174259-22c00200-c26e-11e8-8057-13429a9d168b.png)

**Comment by randy3k** [comment]
Just added support of disabling `ctrl+p`.

https://github.com/randy3k/Terminus/blob/20899d7a301429215bbb4b67c743ad3cd793b732/Terminus.sublime-settings#L75-L75

**Comment by randy3k** [comment]
Ai....`disable_keys` may sound confusing. `presist_keys` maybe a better wording.
