### ISSUE TITLE
Git_Bash for Windows via Terminus

### ISSUE THREAD

**Issue by DAV9854** [randy3k/Terminus#56]
I am trying to get _Terminus_ to open _git-bash_ instead of the windows _command prompt_ with absolutely zero luck. Any one know how this can be done?

**Comment by randy3k** [comment]
You will need to point `cmd` argument to the path to the git bash.

**Comment by DAV9854** [comment]
I've tried doing so.
`        {
            "name": "Git-Bash",
            "cmd": "git-bash.exe",
            "env": {},
            "enable": true,
            "default": true,
            "platforms": ["windows"]
        },
        {
            "name": "Command Prompt",
            "cmd": "cmd.exe",
            "env": {},
            "enable": true,
            "default": false,
            "platforms": ["windows"]
        },`

**Comment by randy3k** [comment]
Are you sure that the executable is called `git-bash.exe`?

**Comment by DAV9854** [comment]
Yes I am absolutely sure. `C:\Program Files\Git\git-bash.exe`

**Comment by randy3k** [comment]
So you have put the path to it in the PATH environmental variable?

**Comment by DAV9854** [comment]
I've added the `PATH` environmental variables to both the git folder and `mingw64` sub folder. `Git-Bash` opens outside of Sublime3 instead of utilizing your package through a view or panel.

**Comment by randy3k** [comment]
I see. `Git-bash.exe` is not the executable you are looking for. Look for sth like `bash.exe`.

**Comment by DAV9854** [comment]
`git-bash.exe` has to be it. If I use `bash` the windows's linux subsystem terminal activates instead. 
see here: https://gitforwindows.org/

![image](https://user-images.githubusercontent.com/10591195/46822908-c1faf400-cd5a-11e8-8315-a93d3096b12b.png)

**Comment by randy3k** [comment]
there should be a `bash.exe` inside the directory `bin` or `mingw64` or somewhere.

**Comment by DAV9854** [comment]
I just found it. I added the `bin` dir to the `PATH` and updated the `cmd:` to `sh`. I couldn't set the `cmd` to bash or else it would run the linux subsystem shell windows added. 

Thanks for your help!

**Comment by randy3k** [comment]
Oh, I was wrong. It should be `sh.exe`. :)

**Comment by DAV9854** [comment]
Haha `: )` regardless you led me to the correct `dir`. Good work.

**Comment by esyede** [comment]
This is my (working) config for git bash, I don't know if it's the correct way or not but it works for me:

```json
{
    "default_config": {
        "linux": null,
        "osx": null,
        "windows": "git-bash", // must be identical with the shell config name
    },
    "shell_configs": [
        {
            "name": "git-bash", // i mean, this one
            "cmd": ["D:/Laragon/bin/git/bin/bash.exe"], // you need to adjust this too
            "env": {},
            "enable": true,
            "default": true,
            "platforms": ["windows"],
        }
    ],
    "theme": "darkside",
}
```



<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/19880d54-f3a3-474d-af05-1bff8263b5f0" />
