### ISSUE TITLE
How to disable trailing whitespaces in panel mode.

### ISSUE THREAD

**Issue by bantya** [randy3k/Terminus#6]
Hi, I have posted a question regarding this package on [sublime forum](https://forum.sublimetext.com/t/finally-a-multi-platform-terminal-running-in-sublime-text/37560/51), but I think I did not explained it very clearly there. So, like many other people, I like to keep the trailing spaces activated while coding.

I use your package **Terminus** (formerly Console and SublimelyTerminal) and must say that it is a must for sublime users.

Formerly with the package when was named **Console**, it supported only the tab view mode, it was highlighting the trailing spaces in the Console tab. I managed to remove the trailing slashes for the **tab view** by adding `"highlight_trailing_whitespace": false,` to the `Plain text` syntax specific settings:

![image](https://user-images.githubusercontent.com/16685565/41806210-4c40d6aa-76d7-11e8-9da7-62db7f0d4da7.png)

When the package was named **SublimelyTerminal**, you added the panel view to the package. It works great, but I can't figure out how to disable the trailing whitespaces for the **panel view** which looks quite unconsistent with the tab view mode:

![image](https://user-images.githubusercontent.com/16685565/41807517-43f56e3c-76ed-11e8-8e3f-22ece583d731.png)

My question is, is there any way to disable the highlighting trailing spaces while in the panel view mode, so that people can use Terminus consistently in both the modes.

**Comment by randy3k** [comment]
Are you using [this](https://github.com/p3lim/sublime-highlight-trailing-whitespace)?

**Comment by bantya** [comment]
Yes I am using exactly the same package and looks like what you suggested is the only way to address the issue currently.

**Comment by randy3k** [comment]
How did you enable it for all packages? There is no option for doing so!?

**Comment by randy3k** [comment]
You could use `view_settings` as a workaround. However, ideally, this issue should be fixed in that package because the settings should not be applied to all views.

https://github.com/randy3k/Terminus/blob/4e948dbb667e37fa7d5cc7fcd2b02483cbe736bd/Terminus.sublime-settings#L78-L78

**Comment by randy3k** [comment]
The bug has been fixed in upstream.
