### ISSUE TITLE
[Question] Any way to open multiple shell's from the Panel

### ISSUE THREAD

**Issue by ggedde** [randy3k/Terminus#62]
I know I can open multiple by open new Tabs, but I would like to be able to start a new shell from the Panel.  Would be nice to add with a shortcut like cmd + t or since we open it with alt+` maybe it is alt+shift+` and switch panels like alt+cmd+{left or right}.

Another idea that might be easier is when I click on the Panel Icon in the status bar it gives me options like 
- Output: Linter
- Output: Terminus

You could just add others like:
- Output: Linter
- Output: Terminus
- Output: Terminus 2
- Output: Terminus 3
- Output: Terminus[New]

**Comment by VaelVictus** [comment]
Tabbed panels is my #1 feature request, I would love to see this so I can dump cmder!

**Comment by CheatEx** [comment]
I've kind of emulated multiple panel tabs with the `panel_name` command argument. You can pass it to both `terminus_open` and `toggle_terminus_panel` commands.

For example I've created a separate panel for my Figwheel development by introducing an init command:
```
{
"caption": "Terminus: Run Figwheel.main",
"command": "terminus_open",
"args"   : {
    "cmd": ["lein", "fig:dev"],
    "cwd": "${project_path}/../",
    "config_name": "Default",
    "panel_name": "fig:dev"
}
```
and a keyboard shortcut
```
{ 
"keys": ["alt+2"], 
"command": "toggle_terminus_panel", 
"args": {"panel_name": "fig:dev"} 
}
```

Downside: it's pretty much hardcoded in Sublimes's global configuration and requires a lot of typing to  introduce a new window kind-of-tab.

**Comment by randy3k** [comment]
It is supported in v0.2.21. If existing panel with the same name is found, the new panel will be named as `{panel_name} 2`
