### ISSUE TITLE
ANSI colour reset has stopped working in PS1

### ISSUE THREAD

**Issue by frou** [randy3k/Terminus#66]
![screenshot 2018-11-12 at 08 24 14](https://user-images.githubusercontent.com/172663/48335007-5efbc600-e654-11e8-9b01-de2aac7111e2.png)

In the above screenshot, I would expect the typed `xxxxxxxxxxx` to be uncoloured. It seems the ANSI escape code to reset color, `\e[0m`, is not being correctly applied when it's in the prompt.

It's working OK outside of the prompt:

![screenshot 2018-11-12 at 08 29 30](https://user-images.githubusercontent.com/172663/48335260-227c9a00-e655-11e8-8f73-4c3548525395.png)

Sublime 3180
Terminus 0.2.14
macOS 10.14.1
bash 3.2 (stock) and 4.4.23 (homebrew)

**Comment by frou** [comment]
Yes, using Terminal.app it still works as expected

**Comment by randy3k** [comment]
Yap, I could reproduce it now. Working on a fix.

**Comment by randy3k** [comment]
6881a09b0299287f284a4d4dd4a2d1acc29bef1f should fix it.

**Comment by agilesteel** [comment]
It is fixed indeed. Thx!

**Comment by frou** [comment]
Confirmed. Thank you
