### ISSUE TITLE
Windows - can't configure terminal to be powershell

### ISSUE THREAD

**Issue by s-c-p** [randy3k/Terminus#69]
If I do 

```
{
    "terminal": "powershell.exe"
}
```

in  Preferences > Package Settings > Package Control > Settings - User

I still get cmd.exe as terminal, I want powershell, how can we achieve this?

**Comment by randy3k** [comment]
You should check the settings for Terminus, not Package Control.

**Comment by s-c-p** [comment]
Wow, okay, thanks! I think this (`Ctrl`+`Shift`+`P` -> terminus sett -> `Enter`) should be included in the README docs under a sub-heading like **Change Default Shell**.
