### ISSUE TITLE
Right-click -> Paste

### ISSUE THREAD

**Issue by urmilparikh** [randy3k/Terminus#7]
Thank you for this long-awaited plugin. I'm using it regularly.

A minor issue I face is that the Paste option from right-click menu doesn't work. Copy works though.

![image](https://user-images.githubusercontent.com/10322815/41886069-581f9c98-7918-11e8-8a8d-5e023df6ab65.png)

**Comment by randy3k** [comment]
You are right. The paste from the menu is expected to be not working, you need to to `ctrl+v` (linux/windows) or `super+v` (macOS).

**Comment by randy3k** [comment]
You know what, I have just pushed a commit to address this, 854badb.

**Comment by urmilparikh** [comment]
Wow! that was fast!!

**Comment by randy3k** [comment]
Coz I am working on it (though not related to this issue).
