### ISSUE TITLE
Scroll up/down with keyboard

### ISSUE THREAD

**Issue by wviechtb** [randy3k/Terminus#78]
Thanks for this nice sublime package! One thing I can't get to work is to scroll within Terminus using the keyboard. In many terminal emulators, `shift+pageup` and `shift+pagedown` does this. But with these key combos, I just see `2~` and `;2~` in Terminus. Is there a way of making this work? I am on Linux in case this matters.

**Comment by randy3k** [comment]
It could be easily done by overwriting the keybindings for the corresponding keys:

```
    { "keys": ["shift+pageup"], "command": "scroll_lines", "args" : {"amount": 50.0}, "context": [{"key": "terminus_view"}] },
    { "keys": ["shift+pagedown"], "command": "scroll_lines", "args" : {"amount": -50.0}, "context": [{"key": "terminus_view"}] }
```

**Comment by wviechtb** [comment]
Works like a charm! Thanks for the quick response.

**Comment by Endermanbugzjfc** [comment]
This issue deserves a pin.
