### ISSUE TITLE
[BUG] If the the tested program goes in segmentation fault terminus crashes

### ISSUE THREAD

**Issue by jacoporoveda** [randy3k/Terminus#79]
I've launched a test program in c and for some errors the program goes in segmentation fault, but terminus instead of reporting the issue just crashes.

Here a screen capture of the issue.

<img width="1440" alt="schermata 2019-01-16 alle 10 12 36" src="https://user-images.githubusercontent.com/45854863/51238654-b3cefc00-1977-11e9-87db-689adf449dec.png">

**Comment by randy3k** [comment]
It is a known issue of Sublime. It has been fixed with the dev channel ST. You could upgrade to it if you have a license.
