### ISSUE TITLE
Package not listed when using "Install package"

### ISSUE THREAD

**Issue by brupelo** [randy3k/Terminus#8]
@randy3k Randy, hiya, I've tried to install your new package on windows7+ST3156 but it won't be listed.

![video](https://dl.dropboxusercontent.com/s/jthrlisco2m05w2/2018-06-28_14-21-08.gif)

Any idea why is that? Ty

**Comment by pradyunsg** [comment]
Same issue.

**Comment by randy3k** [comment]
I have just released it to Package Control. It may take a while for Package Control to load it.
