### ISSUE TITLE
Cannot open terminal window.

### ISSUE THREAD

**Issue by asmentis** [randy3k/Terminus#88]
None of the following are opening a terminal window for me:

Ctrl-Shift-P:
- Open Default Shell in Panel
- Open Default Shell in View
- List Shells
- Toggle Panel

This worked previously (about a week or two ago).

**Comment by randy3k** [comment]
Is there any error message in the sublime console?

**Comment by asmentis** [comment]
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\Terminus\terminus\commands.py", line 95, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(*args, **kwargs))
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\Terminus\terminus\commands.py", line 181, in run_async
    raise Exception("{} does not exist".format(cwd))
Exception: C:\WINDOWS\system32\config\systemprofile does not exist

**Comment by asmentis** [comment]
Hmmm...it's working again. Looks like maybe a permissions problem?

**Comment by asmentis** [comment]
When attempted from other file locations, that last line is:

Exception: %USERPROFILE% does not exist

But it does exist...must be something with my environment/permissions.

**Comment by asmentis** [comment]
Fixed it by explicitly setting HOME and USERPROFILE paths in Environment Variables.

**Comment by randy3k** [comment]
Not sure why it was causing troubles to you. I have never encountered that.

**Comment by asmentis** [comment]
It looks like it wasn't properly expanding the %USERPROFILE% environment variable. I can't explain it either, but your tip to look at the error messages was key to fixing it. Thanks.
