### ISSUE TITLE
Not opening in cwd

### ISSUE THREAD

**Issue by mtzirkel** [randy3k/Terminus#90]
I am running sublimetext on manjaro and I am not able to open a terminal in my current working directory. My shell settings look like this:
{
"shell_configs": [
        {
            "name": "Zsh",
            "cmd": ["zsh", "-i", "-l"],
            "env": {},
            "enable": true,
            "default": true,
            "platforms": ["linux", "osx"]
        },
    ],
    "256color": true,
    "unix_term": "linuxunix-256",

}

And my keybinding looks like:
[
     {
        "keys": ["ctrl+alt+t"], "command": "terminus_open", "args": {
            "config_name": "Default",
            "cwd": "${file_path:${folder}}",
            "title": "Terminal"
        }
    }
]

Is there something special in the file path for arch linux users that I am missing.  I also wonder if it is a setting issue as now when I use the command pallet I cannot open a terminal. Thanks in advance

**Comment by mtzirkel** [comment]
Figured it out

**Comment by michael-fang** [comment]
Hi,
I am having the same issue. even though cwd is set properly, the terminus doesn't open with that directory. would you mind share how you fix it?

**Comment by matreshkin** [comment]
I had the  same issue with bash - "cd" command in my ~/.bashrc overrode the cwd in command args.
