### ISSUE TITLE
⌘+K to clear the terminal

### ISSUE THREAD

**Issue by juliendargelos** [randy3k/Terminus#92]
Hi,
I cannot go without `⌘+K` to clear the terminal on Mac OS (different from the `clear` command since it actually empty the screen).
It would be cool to have it on Terminus too 🙂

**Comment by randy3k** [comment]
How about `crtl+k`?

**Comment by Afrowave** [comment]
`crtl+k` does not work either on the Mac. What really I think should happen is a view scroll to the point where only the prompt is visible.

**Comment by randy3k** [comment]
I am not sure why `ctrl + k` doesn’t work for you. Did you override the key accidentally?

**Comment by Afrowave** [comment]
Yes. `ctrl+k` is disabled and there is a nice explanation why. 😄

**Comment by notiv-nt** [comment]
Not the best solution, and works only on the first terminal found, but so far it works:


### Packages/User/terminal-clear.py
```
import sublime, sublime_plugin

class TtTerminalClearCommand(sublime_plugin.WindowCommand):
  def run(self):
    self.window.run_command("terminus_send_string", { "string": "clear\n", })
    # self.window.run_command("terminus_clear_history")
```

### Keybindings:
```
  {
    "keys": ["super+k"],
    "command": "tt_terminal_clear",
    "context": [{"key": "terminus_view"}]
  }
```

**Comment by randy3k** [comment]
What's the problem with `ctrl+l`?

**Comment by notiv-nt** [comment]
`ctrl+l` > win
`super+k` > mac

**Comment by randy3k** [comment]
`ctrl+l` is a universal vt100 sequence to clear the terminal.

**Comment by randy3k** [comment]
> `terminal.app` (macos) `ctrl+l` doesn't work

It works for me though..

**Comment by notiv-nt** [comment]
Ok, problem with dvorak-layout on mac `ctrl+l` doesn't work (`ctrl+p` in my case)
But `⌘+K` works well

**Comment by Afrowave** [comment]
I am on Mac OS X 10.11.6 and `ctrl + l` on ST 3193 works as it should.

**Comment by juliendargelos** [comment]
- `ctrl+l`  acts as the `clear` command: it scrolls until all previous lines are hidden.
- `⌘+K` **actually flushes** the terminal view.

Usually, when I'm looking to server logs, I remove everything in the terminal with `⌘+K`, I send a request to the server, then I can scroll to the very top of the terminal view and see just my request's logs without pollution.

### `clear`

![clear](https://user-images.githubusercontent.com/3743321/53814682-5c551180-3f60-11e9-859f-9ad34af81d47.gif)

### `ctrl+l`

![ctrl-l](https://user-images.githubusercontent.com/3743321/53814799-a5a56100-3f60-11e9-836d-41477add3b8d.gif)

### `⌘+K`

![super-k](https://user-images.githubusercontent.com/3743321/53814839-b7870400-3f60-11e9-8cfe-f016d34a9f06.gif)

**Comment by randy3k** [comment]
Oh, I see. There is a command called `Terminus: Clear History`. The combination of `ctrl+l` and `Clear History` would give you the same behaviour.

**Comment by juliendargelos** [comment]
Okay, using the [Chain Of Command](https://github.com/jisaacks/ChainOfCommand) package I added the following key binding. It's not perfect: most of the time, two key presses are needed, probably because of the scroll animation that occur while clearing.

```json
{
  "keys": ["super+k"],
  "command": "chain",
  "args": {
    "commands": [
      ["terminus_keypress", {"key": "l", "ctrl": true}],
      ["terminus_clear_history"]
    ]
  }
}
```

A dedicated command (maybe `terminus_flush` ?) would be better 🙂

**Comment by notiv-nt** [comment]
> A dedicated command (maybe terminus_flush ?) would be better 🙂
yes
and, can you tell:

I have 
```
{ "keys": ["super+k"], "command": "run_macro_file", "args": { "file": "Packages/User/Macros/Scroll Up.sublime-macro" } },
```

And the same keys for clear terminal.  What "scope" do i need to add ? And where?

**Comment by randy3k** [comment]
You need to do it twice because both commands are asynchronous. I agree, I dedicated command is needed for this purpose.

**Comment by randy3k** [comment]
With the current master, both `clear` and `reset` will clear the scrollback history as expected.

PS: macOS terminal doesn't following the standard to clear the scrollback history when `reset` or `clear` is executed.

**Comment by faelin** [comment]
For users looking to clear the scrollback buffer:
```
{
  "keys": ["super+k"],
  "command": "terminus_reset",
},
```

**Comment by rising-stark** [comment]
> 
> {
>   "keys": ["super+k"],
>   "command": "run_macro_file",
>   "args": { "file": "Packages/User/Macros/Scroll Up.sublime-macro" }
> }
> 
> 
> And the same keys for clear terminal. What "scope" do i need to add ? And where?

@notiv-nt hey did u find the solution to add scopes yet? I am facing the same issue here

**Comment by notiv-nt** [comment]
@rising-stark idk, i moved to vscode

In sublime i have only these lines associated with terminus
```
{ "keys": ["ctrl+j"], "command": "terminus_keypress", "args": {"key": "c", "ctrl": true}, "context": [{"key": "terminus_view"}] },
{ "keys": ["super+k"], "command": "terminus_keypress", "args": {"key": "l", "ctrl": true}, "context": [{"key": "terminus_view"}] }, 
```

**Comment by rising-stark** [comment]
@notiv-nt oh. okay. not an issue. appreciate the quick reply

**Comment by kmooventhan98** [comment]
where do i need to add the command
