### ISSUE TITLE
$file from build system not expanded

### ISSUE THREAD

**Issue by daviehh** [randy3k/Terminus#93]
I would like to use Terminus as a build system (for julia), where the build command is `include("/path/to/file")`. The following build system

```
{
    "string": "include($file)\n",
    "target":"terminus_send_string",
    "selector": "source.Julia"
}
```

sends `$file` as-is, i.e. in the Terminus window, I see `include($file)` instead of `include("/path/to/file")`. Is it a bug or such case should be handled by a build script as the "Advanced Example" section [here](https://www.sublimetext.com/docs/3/build_systems.html#advanced_example)? Thanks a lot!

**Comment by randy3k** [comment]
It is the expected behavior as `terminus_send_string` does not resolve any variables. You can try my another package https://github.com/randy3k/SendCode

**Comment by daviehh** [comment]
Got it, thanks a lot!
