### ISSUE TITLE
blue can be hard to see

### ISSUE THREAD

**Issue by daviehh** [randy3k/Terminus#94]
https://github.com/randy3k/Terminus/blob/c2b7b02144bcc14bad3b96534d2b191c5347aba0/Terminus.sublime-color-scheme#L14

This blue is difficult to see, e.g. the julia `]` (pkg) prompt looks like this: (macOS)
<img width="590" alt="Screen Shot 2019-03-11 at 10 06 36 PM" src="https://user-images.githubusercontent.com/25255906/54169711-3fca4500-444a-11e9-9e95-d2086e8a7d35.png">

propose to change to e.g. `#4F8EE3` (atom/juno setting)

<img width="590" alt="Screen Shot 2019-03-11 at 10 06 59 PM" src="https://user-images.githubusercontent.com/25255906/54169730-51135180-444a-11e9-9cc8-a8c7adcb4e73.png">

Not sure if it's specific to mac or also applies to linux/windows. Thanks!

**Comment by randy3k** [comment]
You could choose a different theme by using `Terminus Utilities`

**Comment by daviehh** [comment]
Thanks a lot!
