### ISSUE TITLE
Terminus is duplicating the right-click 'Open URL' that Sublime already provides

### ISSUE THREAD

**Issue by frou** [randy3k/Terminus#98]
When right-clicking a URL, an _'Open ...'_ item is shown twice.

![Screenshot 2019-03-17 at 20 46 02](https://user-images.githubusercontent.com/172663/54497938-8f9c8680-48f8-11e9-98a5-507aa666d61c.png)

They come from:

`Default/Context.sublime-menu` -> `OpenContextUrlCommand`

and

`Terminus/Context.sublime-menu` -> `TerminusOpenContextUrlCommand`

Should Terminus's one be there?

**Comment by randy3k** [comment]
The built in command doesn’t work if the website spans more than one line. We ship our version of `Open URL ` for those cases. And I found no way to hide the built in one.

**Comment by frou** [comment]
Ok, but should it show in normal views? That screenshot is editing a JSON file and not a terminal.

**Comment by randy3k** [comment]
Oh, you are right. It shouldn’t appear in a regular view.

**Comment by frou** [comment]
Thank you Randy
